Repository ymcatwincities/openy, pull requests merged in 2018-02, with the labels that each got.

#954 #952 PHP Notice: Undefined offset on every page load
  modules/custom/openy_font/openy_font.module
Labels: PR: Code Reviewed, Type: Bug

#956 [OYPD-640] Adding fixed width to logo to fix IE issue
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_header.scss
Labels: PR: Code Reviewed, PR: Tested

#958 957 - Fix Notice: Undefined index: date in openy_group_schedules form
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
Labels: PR: Code Reviewed, PR: Tested

#961 Lily theme improvements and fixes
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/misc/_forms.scss
  themes/openy_themes/openy_lily/sass/misc/_templates.scss
  themes/openy_themes/openy_lily/sass/modules/_dialog.scss
  themes/openy_themes/openy_lily/sass/modules/_schedules.scss
  themes/openy_themes/openy_lily/sass/paragraphs/_amenities.scss
  themes/openy_themes/openy_lily/templates/webform/webform--contact.html.twig
Labels: PR: Code Reviewed, PR: Tested

#962 [OYPD-638] Improve theming of Lily theme (camp header, news page)
  themes/openy_themes/openy_lily/templates/node/node--camp--full.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--listing-news-posts--block.html.twig
Labels: PR: Code Reviewed, PR: Tested

#949 [OYPD-646] Adding entity update hook to unpublish categories when the p…
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.module
  modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.module
  modules/openy_features/openy_node/modules/openy_node_class/openy_node_class.module
  modules/openy_features/openy_node/src/BatchNodeUpdate.php
Labels: PR: Needs Review

#953 [OYPD-645] Featured Highlights paragraph from LI to OpenY.
  docs/Content structure/Paragraphs/Featured Highlights.md
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/block_content.type.featured_highlights_block.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/core.entity_form_display.block_content.featured_highlights_block.default.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/core.entity_view_display.block_content.featured_highlights_block.default.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.field.block_content.featured_highlights_block.field_block_content.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.field.block_content.featured_highlights_block.field_featured_hl_block_image.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.field.block_content.featured_highlights_block.field_featured_hl_block_link.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.storage.block_content.field_featured_hl_block_image.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.storage.block_content.field_featured_hl_block_link.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/language.content_settings.block_content.featured_highlights_block.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/openy_block_featured_highlights.features.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/openy_block_featured_highlights.info.yml
  modules/openy_features/openy_prgf/config/install/openy_prgf.settings.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/core.entity_form_display.paragraph.featured_highlights.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/core.entity_view_display.paragraph.featured_highlights.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/field.field.paragraph.featured_highlights.field_prgf_block_ref_unlim.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/field.field.paragraph.featured_highlights.field_prgf_grid_style.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/field.field.paragraph.featured_highlights.field_prgf_title.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/field.storage.paragraph.field_prgf_block_ref_unlim.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/paragraphs.paragraphs_type.featured_highlights.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.features.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.module
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/templates/openy-basic-block.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/templates/openy-date-block.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/templates/openy-featured-highlights-block.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/templates/openy-simple-block.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/templates/paragraph--featured-highlights--default.html.twig
  modules/openy_features/openy_prgf/openy_prgf.install
  openy.info.yml
  tests/features/paragraphs/featured_highlights_paragraphs.feature
  tests/files/child.jpg
  tests/files/health.jpg
  tests/files/swim_lessons.jpg
Labels: PR: Code Reviewed, PR: Tested

#968 Fix Unsupported operand types error with missing instructor_options variable
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
Labels: PR: Code Reviewed, PR: Tested

#965 Theme Secondary description and sidebar prgf
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/base/_colors.scss
  themes/openy_themes/openy_lily/sass/paragraphs/_paragraphs.scss
Labels: PR: Code Reviewed, PR: Tested

#971 Fix 'results' is an invalid render array key error
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
Labels: PR: Code Reviewed, PR: Needs testing

#966 Update Drupal Core to 8.4.5
  composer.json
  composer.lock
Labels: PR: Needs Review, PR: Needs testing
