Repository ymcatwincities/openy, pull requests merged in 2018-11, with the labels that each got.

#1362 Fix composer.json
  composer.json
  composer.lock
Labels: Severity: Critical

#1356 [OPENY-179] Mark location_finder module as deprecated
  modules/custom/location_finder/location_finder.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1357 [OPENY-182] Update Open Y modules  names, packages, versions
  modules/custom/openy_autocomplete_path/openy_autocomplete_path.info.yml
  modules/custom/openy_campaign/modules/openy_campaign_color/openy_campaign_color.info.yml
  modules/custom/openy_campaign/modules/openy_campaign_reference_with_text/openy_campaign_reference_with_text.info.yml
  modules/custom/openy_campaign/openy_campaign.info.yml
  modules/custom/openy_development/openy_development.info.yml
  modules/custom/openy_gxp/openy_gxp.info.yml
  modules/custom/openy_interstitial/openy_interstitial.info.yml
  modules/custom/openy_repeat/openy_repeat.info.yml
  modules/custom/openy_repeat_entity/openy_repeat_entity.info.yml
  modules/custom/personify/personify.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/openy_demo_nevent.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/openy_demo_nnews.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tnews/openy_demo_tnews.info.yml
  modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.info.yml
  modules/openy_features/openy_node/modules/openy_node_mbrshp/openy_node_mbrshp.info.yml
  modules/openy_features/openy_node/modules/openy_node_program/openy_node_program.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_latest/openy_prgf_news_latest.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_listing/openy_prgf_news_listing.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_pgm_reg/openy_prgf_pgm_reg.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_fitness_category/openy_txnm_fitness_category.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1361 [OPENY-191] Update packages list form
  modules/custom/openy_system/src/Form/OpenyModulesListForm.php
  openy.packages.yml
Labels: PR: Code Reviewed, PR: Tested

#1360 [OPENY-178] Include modules in package
  modules/custom/openy_development/openy_development.info.yml
  openy.packages.yml
Labels: PR: Needs Work

#1368 Move shared field storage to block package module
  modules/openy_features/openy_block/config/install/field.storage.block_content.field_block_content.yml
Labels: PR: Code Reviewed, PR: Tested

#1358 [OPENY-180] Fix broken location finder blocks on locations page
  openy.install
  openy.profile
Labels: PR: Code Reviewed

#1340 [OPENY-162] Decouple OpenY FAQ paragraph
  modules/custom/openy_field_faq/openy_field_faq.info.yml
  modules/custom/openy_field_faq/src/Plugin/Field/FieldFormatter/FaqDefault.php
  modules/custom/openy_field_faq/src/Plugin/Field/FieldType/FaqItem.php
  modules/custom/openy_field_faq/src/Plugin/Field/FieldWidget/FaqDefault.php
  modules/custom/openy_system/src/OpenyModulesManager.php
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/core.entity_form_display.paragraph.faq.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/core.entity_view_display.paragraph.faq.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/field.field.paragraph.faq.field_qa.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/field.storage.paragraph.field_qa.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/openy_prgf_faq.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/openy_prgf_faq.install
  openy.installation_types.yml
  openy.packages.yml
Labels: PR: Code Reviewed, PR: Tested

#1370 [OPENY-215] Enable missed migrations for complete preset
  modules/openy_features/openy_demo_content/modules/openy_demo_menu/modules/openy_demo_menu_main/config/install/migrate_plus.migration.menu_link_main.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.news_landing.yml
Labels: PR: Code Reviewed, PR: Tested

#1373 [OPENY-217] Enable fontyourface in profile
  openy.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1372 [OPENY-216] Change to Open Y to fix home page
  modules/openy_features/openy_demo_content/modules/openy_demo_ahb/config/install/migrate_plus.migration.entity_ahb.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nalert/config/install/migrate_plus.migration.node_alert_standard_extended.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nhome_alt/config/install/migrate_plus.migration.node_home_alt_landing.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.node_landing_extended.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.node_landing_standard.yml
Labels: PR: Code Reviewed, PR: Tested

#1376 [OPENY-219] Enable openy_map when locations package is enabled
  modules/openy_features/openy_prgf/modules/openy_prgf_loc_finder/openy_prgf_loc_finder.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1380 [OPENY-220] Fix update after config move
  modules/openy_features/openy_prgf/modules/openy_prgf_loc_finder/openy_prgf_loc_finder.install
Labels: PR: Code Reviewed

#1379 [OPENY-220] Fix config import errors
  modules/openy_features/openy_node/openy_node.install
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.install
  modules/openy_features/openy_prgf/modules/openy_prgf_grid_content/openy_prgf_grid_content.install
Labels: PR: Code Reviewed, Type: Bug

#1383 [OPENY-192] Fix nonexisting service error when unistalling packages
  docs/Development/Module Develompent.md
  modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/openy_prgf_camp_menu.install
  modules/openy_features/openy_prgf/modules/openy_prgf_class_location/openy_prgf_class_location.install
  modules/openy_features/openy_prgf/modules/openy_prgf_class_sessions/openy_prgf_class_sessions.install
  openy.profile
Labels: PR: Code Reviewed, PR: Tested

#1381 Replaced hardcoded HTML ids in Carnation theme to not break inheritance of CSS styles and JS logic in sub-themes
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/js/openy_carnation.js
  themes/openy_themes/openy_carnation/src/scss/modules/_footer.scss
  themes/openy_themes/openy_carnation/templates/block/block--local-tasks-block.html.twig
  themes/openy_themes/openy_carnation/templates/block/block--system-menu-block--footer-menu-right.html.twig
  themes/openy_themes/openy_carnation/templates/block/block--views-block--alerts-header-alerts.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1392 [OPENY-1389]: Carnation mobile menu and map on Locations and Join pages
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
Labels: PR: Code Reviewed, PR: Tested

#1393 [OPENY-1389]: Carnation mobile menu and map on Locations and Join pages (backport to 8.x-1.x)
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
Labels: PR: Code Reviewed, PR: Tested

#1394 Fix openy_socrates
  modules/custom/openy_socrates/src/OpenySocratesCompilerPass.php
Labels: PR: Code Reviewed, PR: Needs Testing
