Repository ymcatwincities/openy, pull requests merged in 2018-06, with the labels that each got.

#1061 [813] Membership calculator issues
  modules/custom/location_finder/src/LocationFinderDataWrapper.php
  modules/custom/openy_calc/openy_calc.services.yml
  modules/custom/openy_calc/src/CalcDataWrapper.php
  modules/custom/openy_calc/src/DataWrapperBase.php
  modules/custom/openy_data_wrapper/src/DataWrapper.php
  modules/custom/openy_map/js/map.js
Labels: Type: Bug

#1074 Ci extended
  .github/PULL_REQUEST_TEMPLATE.md
  composer.json
  composer.lock
  drupal-org.make
  modules/custom/location_finder/src/LocationFinderDataWrapper.php
  modules/custom/openy_calc/openy_calc.services.yml
  modules/custom/openy_calc/src/CalcDataWrapper.php
  modules/custom/openy_calc/src/DataWrapperBase.php
  modules/custom/openy_data_wrapper/src/DataWrapper.php
  modules/custom/openy_development/config/install/domain.record.lily_openy_cibox_tools.yml
  modules/custom/openy_development/config/install/domain.record.openy_cibox_tools.yml
  modules/custom/openy_development/config/install/domain.settings.yml
  modules/custom/openy_development/config/install/domain_theme_switch.settings.yml
  modules/custom/openy_development/config/install/field.field.user.user.field_domain_admin.yml
  modules/custom/openy_development/config/install/field.storage.user.field_domain_admin.yml
  modules/custom/openy_development/openy_development.features.yml
  modules/custom/openy_development/openy_development.info.yml
  modules/custom/openy_map/js/map.js
Labels: PR: DO NOT MERGE

#1060 [OPENY-30] Basic block - component decoupling
  modules/custom/openy_er/README.md
  modules/custom/openy_er/openy_er.info.yml
  modules/custom/openy_er/openy_er.module
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/BlockSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/DefaultSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/NodeSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php
  modules/openy_features/openy_block/modules/openy_block_basic/config/install/field.storage.block_content.field_block_content.yml
  modules/openy_features/openy_block/modules/openy_block_basic/openy_block_basic.info.yml
  modules/openy_features/openy_block/modules/openy_block_basic/openy_block_basic.install
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.storage.block_content.field_block_content.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/config/install/field.field.paragraph.featured_highlights.field_prgf_block_ref_unlim.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.install
  modules/openy_features/openy_prgf/modules/openy_prgf_secondary_description_sidebar/config/install/field.field.paragraph.secondary_description_sidebar.field_prgf_left_column_block.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_secondary_description_sidebar/config/install/field.field.paragraph.secondary_description_sidebar.field_prgf_right_column_block.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_secondary_description_sidebar/openy_prgf_secondary_description_sidebar.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_secondary_description_sidebar/openy_prgf_secondary_description_sidebar.install
  openy.info.yml
  openy.install
Labels: PR: Code Reviewed, PR: Tested

#1076 [OPENY-52] [OPENY-19] Alert and Landing page - content types decoupling
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.info.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.install
Labels: PR: Code Reviewed, PR: Tested

#1081 [OPENY-39] Blog Posts Listing paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_listing/openy_prgf_blog_listing.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_listing/openy_prgf_blog_listing.install
Labels: PR: Code Reviewed, PR: Tested

#1080 [OPENY-38] Amenities paragraphs decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_amenities/openy_prgf_amenities.install
  modules/openy_features/openy_prgf/modules/openy_prgf_location_by_amenities/openy_prgf_location_by_amenities.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_location_by_amenities/openy_prgf_location_by_amenities.install
Labels: PR: Code Reviewed, PR: Tested

#1090 [1078]: menu styles when there is small amount of items
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css.map
  themes/openy_themes/openy_rose/scss/modules/_header.scss
Labels: Level: Novice, Severity: Minor, Type: Bug

#1082 [OPENY-50] Featured Blog Posts paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_blogs/openy_prgf_featured_blogs.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_blogs/openy_prgf_featured_blogs.install
Labels: PR: Code Reviewed, PR: Tested

#1098 Fix possible errors for theme alters functions
  themes/openy_themes/openy_rose/openy_rose.theme
Labels: PR: Code Reviewed, Type: Bug

#1099 [OPENY-43] Categories Listing paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_categories_listing/openy_prgf_categories_listing.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_categories_listing/openy_prgf_categories_listing.install
Labels: PR: Code Reviewed, PR: Tested

#1100 [OPENY-44] [OPENY-45] Classes Listing paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.install
Labels: PR: Code Reviewed, PR: Tested

#1102 [OPENY-40] Branches popup (All) decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_branches_popup_all/openy_prgf_branches_popup_all.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_branches_popup_all/openy_prgf_branches_popup_all.install
Labels: PR: Code Reviewed, PR: Tested

#1105 [OPENY-46] Class location paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_class_location/openy_prgf_class_location.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_class_location/openy_prgf_class_location.install
Labels: PR: Code Reviewed, PR: Tested

#1106 [OPENY-47] Class Sessions paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_class_sessions/openy_prgf_class_sessions.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_class_sessions/openy_prgf_class_sessions.install
Labels: PR: Code Reviewed, PR: Tested

#1109 [OPENY-49] Embedded GroupEx Pro Schedule paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_embedded_groupexpro_schedule/openy_prgf_embedded_groupexpro_schedule.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_embedded_groupexpro_schedule/openy_prgf_embedded_groupexpro_schedule.install
Labels: PR: Code Reviewed, PR: Tested

#1104 [OPENY-42] Camp menu paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/openy_prgf_camp_menu.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/openy_prgf_camp_menu.install
Labels: PR: Code Reviewed, PR: Tested

#1103 [OPENY-41] Branches popup (Class) paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_branches_popup_class/openy_prgf_branches_popup_class.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_branches_popup_class/openy_prgf_branches_popup_class.install
Labels: PR: Code Reviewed, PR: Tested

#1107 [OPENY-48] Date Block paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_block_date/openy_prgf_block_date.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_block_date/openy_prgf_block_date.install
Labels: PR: Code Reviewed, PR: Tested

#1111 Fix upgrade path for new alert fields
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  openy.install
Labels: PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug

#1079 [OPENY-28] XML sitemap - component decoupling
  modules/custom/openy_upgrade_tool/src/ConfigUpdater.php
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_news/config/install/simple_sitemap.bundle_settings.node.news.yml
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.install
  modules/openy_features/openy_node/openy_node.module
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.module
Labels: PR: Code Reviewed, PR: Tested

#1113 [OPENY-63] Latest blog posts paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_1c/openy_prgf_1c.install
  modules/openy_features/openy_prgf/modules/openy_prgf_2c/openy_prgf_2c.install
  modules/openy_features/openy_prgf/modules/openy_prgf_3c/openy_prgf_3c.install
  modules/openy_features/openy_prgf/modules/openy_prgf_4c/openy_prgf_4c.install
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_latest/openy_prgf_blog_latest.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_latest/openy_prgf_blog_latest.install
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.install
  modules/openy_features/openy_prgf/modules/openy_prgf_secondary_description_sidebar/openy_prgf_secondary_description_sidebar.install
Labels: PR: Code Reviewed, PR: Tested

#1114 [OPENY-63] Latest blog posts (branch) paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_branch/openy_prgf_blog_branch.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_branch/openy_prgf_blog_branch.install
Labels: PR: Code Reviewed, PR: Tested

#1115 [OPENY-63] Latest blog posts (camp) paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_camp/openy_prgf_blog_camp.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_camp/openy_prgf_blog_camp.install
Labels: PR: Code Reviewed, PR: Tested

#1128 [OPENY-64] Grid columns & Grid Content decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_grid_content/openy_prgf_grid_content.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_grid_content/openy_prgf_grid_content.install
Labels: PR: Code Reviewed, PR: Tested

#1119 [OPENY-62] Featured News Posts decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_news/openy_prgf_featured_news.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_news/openy_prgf_featured_news.install
Labels: PR: Code Reviewed, PR: Tested

#1120 [OPENY-62] Latest news posts decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_news_latest/openy_prgf_news_latest.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_latest/openy_prgf_news_latest.install
Labels: PR: Code Reviewed, PR: Tested

#1116 [OPENY-63] Blogs decoupling
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.info.yml
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.install
Labels: PR: Code Reviewed, PR: Tested

#1117 [OPENY-63] Blog category decoupling
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.install
Labels: PR: Code Reviewed, PR: Tested

#1121 [OPENY-62] Latest news posts (branch) decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_news_branch/openy_prgf_news_branch.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_branch/openy_prgf_news_branch.install
Labels: PR: Code Reviewed, PR: Tested

#1123 [OPENY-62] Latest news posts (camp) decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_news_camp/openy_prgf_news_camp.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_camp/openy_prgf_news_camp.install
Labels: PR: Code Reviewed, PR: Tested

#1124 [OPENY-62] News Posts Listing decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_news_listing/openy_prgf_news_listing.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_listing/openy_prgf_news_listing.install
Labels: PR: Code Reviewed, PR: Tested

#1125 [OPENY-62] News Post decoupling
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.info.yml
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.install
Labels: PR: Code Reviewed, PR: Tested

#1126 [OPENY-62] News category decoupling
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/openy_txnm_news_category.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/openy_txnm_news_category.install
Labels: PR: Code Reviewed, PR: Tested
