Repository ymcatwincities/openy, pull requests merged in 2018-12, with the labels that each got.

#1396 "Class 'Drupal\openy_moderation_wrapper\Drupal' not found" error
  modules/custom/openy_moderation_wrapper/src/EntityModerationStatus.php
Labels: PR: Code Reviewed, Type: Bug

#1397 Fix for "Notice: Undefined variable: locations"
  modules/custom/openy_session_instance/src/SessionInstanceManager.php
Labels: PR: Code Reviewed, Type: Bug

#1384 [OPENY-1375] Search icon and form removed from Carnation theme 8.x 2.x
  openy.install
  themes/openy_themes/openy_carnation/config/install/openy_carnation.settings.yml
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/templates/menu/menu--main--primary-menu.html.twig
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1406 Fix bug of Camp menu
  modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/templates/camp-menu.html.twig
  themes/openy_themes/openy_rose/scripts/openy_rose.js
Labels: PR: Code Reviewed, PR: Tested, Type: Bug

#1409 Fix fatal for blog post teasers rendered in openy_rose
  themes/openy_themes/openy_rose/templates/node/node--blog--teaser.html.twig
  themes/openy_themes/openy_rose/templates/paragraph/paragraph--story-card--default.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1408 [OPENY-237] Remove blazy for render icon
  modules/openy_features/openy_media/modules/openy_media_image/config/install/core.entity_view_display.media.image.icon.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
Labels: PR: Code Reviewed, PR: Tested, Type: Bug

#1407 Page of Class content type loading is very long time
  modules/openy_features/openy_prgf/modules/openy_prgf_class_sessions/src/Plugin/Block/ClassSessions.php
Labels: PR: Needs Review, PR: Needs Testing, Type: Bug

#1405 Fix bug query of Popups form
  modules/custom/openy_popups/src/Form/BranchesForm.php
Labels: PR: Needs Review, PR: Needs Testing, Severity: Important, Type: Bug

#1404 issue/1335 added title of the PDF schedules page
  modules/custom/openy_repeat/src/Controller/RepeatController.php
  modules/custom/openy_repeat/src/PDFGenerator.php
Labels: PR: Code Reviewed, PR: Needs Testing

#1416 Fix theming for Open Y Alerts
  modules/openy_features/openy_node/modules/openy_node_alert/scss/openy_node_alert.scss
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/scss/modules.scss
Labels: PR: Code Reviewed, PR: Tested, Type: Task

#1346 Update CSS for better Program Header Image responsiveness
  themes/openy_themes/openy_lily/sass/global/_openy-lily-styles.scss
Labels: PR: Needs Review, PR: Needs Testing

#1305 [YGBW-337] Fix padding issue on taxonomy page
  themes/openy_themes/openy_rose/templates/views/views-view-unformatted--taxonomy_term.html.twig
Labels: PR: Code Reviewed, PR: Tested, Type: Bug
