Repository ymcatwincities/openy, pull requests merged in 2018-08, with the labels that each got.

#1183 [OPENY-81] Camp CT decouling
  modules/custom/openy_schedules/src/Form/SchedulesSearchForm.php
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.info.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.install
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/field.field.node.blog.field_blog_category.yml
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/field.field.node.blog.field_blog_description.yml
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/field.field.node.blog.field_blog_location.yml
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/field.field.node.blog.field_blog_related.yml
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/field.field.node.blog.field_blog_style.yml
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/field.field.node.blog.field_meta_tags.yml
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.info.yml
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.install
  modules/openy_features/openy_node/modules/openy_node_event/config/install/field.field.node.event.field_event_location.yml
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.info.yml
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.install
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_class.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_location.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_plocation.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/paragraphs.paragraphs_type.session_time.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.install
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.module
  themes/openy_themes/openy_lily/openy_lily.theme
  themes/openy_themes/openy_rose/openy_rose.theme
Labels: PR: Code Reviewed, PR: Tested

#1187 [OPENY-88] & [OPENY-89] Program and Program Subcategory decoupling
  modules/openy_features/openy_node/modules/openy_node_activity/config/install/field.field.node.activity.field_activity_category.yml
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.info.yml
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.install
  modules/openy_features/openy_node/modules/openy_node_category/config/install/core.entity_view_display.node.program_subcategory.default.yml
  modules/openy_features/openy_node/modules/openy_node_category/config/install/core.entity_view_display.node.program_subcategory.full.yml
  modules/openy_features/openy_node/modules/openy_node_category/config/install/core.entity_view_display.node.program_subcategory.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_category/config/install/field.field.node.program_subcategory.field_bottom_content.yml
  modules/openy_features/openy_node/modules/openy_node_category/config/install/field.field.node.program_subcategory.field_category_description.yml
  modules/openy_features/openy_node/modules/openy_node_category/config/install/field.field.node.program_subcategory.field_meta_tags.yml
  modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.info.yml
  modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.install
  modules/openy_features/openy_node/modules/openy_node_program/openy_node_program.info.yml
  modules/openy_features/openy_node/modules/openy_node_program/openy_node_program.install
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/responsive_image.styles.social_post_preview.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.info.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.install
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1202 Issue #588 Ymcali faq
  README.md
  composer.json
  modules/custom/openy_ckeditor/js/plugins/ckeditor_alters/plugin.js
  modules/custom/openy_ckeditor/src/Plugin/CKEditorPlugin/CKEditorAlters.php
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.prgf_blog_branch.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.prgf_blog_camp.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/core.entity_form_display.paragraph.faq.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/core.entity_view_display.paragraph.faq.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/field.field.paragraph.faq.field_qa.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/field.storage.paragraph.field_qa.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/config/install/paragraphs.paragraphs_type.faq.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/js/paragraph.js
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/openy_prgf_faq.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/openy_prgf_faq.libraries.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/openy_prgf_faq.module
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/scss/faq.scss
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/src/Plugin/Field/FieldFormatter/FaqDefault.php
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/src/Plugin/Field/FieldType/FaqItem.php
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/src/Plugin/Field/FieldWidget/FaqDefault.php
  openy.install
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/misc/_breadcrumb.scss
  themes/openy_themes/openy_lily/sass/style.scss
  themes/openy_themes/openy_lily/scripts/openy_lily_blog_slider.js
  themes/openy_themes/openy_lily/templates/node/include/node--landing-page--one-column-full.html.twig
  themes/openy_themes/openy_lily/templates/node/node--program--full.html.twig
  themes/openy_themes/openy_lily/templates/node/node--program-subcategory--full.html.twig
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css.map
  themes/openy_themes/openy_rose/openy_rose.theme
  themes/openy_themes/openy_rose/scripts/openy_rose_blog_slider.js
  themes/openy_themes/openy_rose/scss/styles.scss
  themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig
  themes/openy_themes/openy_rose/templates/node/node--program--full.html.twig
  themes/openy_themes/openy_rose/templates/node/node--program-subcategory--full.html.twig
  themes/openy_themes/scss/modules.scss
Labels: Level: Middle, PR: Needs Review, PR: Needs Testing, Severity: Important, Type: Experimental feature

#1204 [OPENY-124] OpenY modules versions and names update
  modules/custom/activenet/activenet.info.yml
  modules/custom/daxko/daxko.info.yml
  modules/custom/embedded_groupexpro_schedule/embedded_groupexpro_schedule.info.yml
  modules/custom/location_finder/location_finder.info.yml
  modules/custom/logger_entity/logger_entity.info.yml
  modules/custom/openy_addthis/openy_addthis.info.yml
  modules/custom/openy_branch_selector/openy_branch_selector.info.yml
  modules/custom/openy_ckeditor/openy_ckeditor.info.yml
  modules/custom/openy_data_wrapper/openy_data_wrapper.info.yml
  modules/custom/openy_daxko2/openy_daxko2.info.yml
  modules/custom/openy_daxko2/openy_daxko2_example/openy_daxko2_example.info.yml
  modules/custom/openy_field_hours/modules/openy_field_custom_hours/openy_field_custom_hours.info.yml
  modules/custom/openy_field_hours/modules/openy_field_holiday_hours/openy_field_holiday_hours.info.yml
  modules/custom/openy_field_hours/openy_field_hours.info.yml
  modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.info.yml
  modules/custom/openy_group_schedules/openy_group_schedules.info.yml
  modules/custom/openy_gtranslate/openy_gtranslate.info.yml
  modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
  modules/custom/openy_map/openy_map.info.yml
  modules/custom/openy_mappings/openy_mappings.info.yml
  modules/custom/openy_migrate/openy_migrate.info.yml
  modules/custom/openy_moderation_wrapper/openy_moderation_wrapper.info.yml
  modules/custom/openy_programs_search/openy_programs_search.info.yml
  modules/custom/openy_redirect/openy_redirect.info.yml
  modules/custom/openy_schedules/openy_schedules.info.yml
  modules/custom/openy_session_instance/openy_session_instance.info.yml
  modules/custom/openy_socrates/openy_socrates.info.yml
  modules/custom/openy_svg_formatter/openy_svg_formatter.info.yml
  modules/custom/openy_system/openy_system.info.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.info.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/openy_block_branch_amenities.info.yml
  modules/openy_features/openy_block/modules/openy_block_custom_simple/openy_block_custom_simple.info.yml
  modules/openy_features/openy_block/modules/openy_block_flexible_content/openy_block_flexible_content.info.yml
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.info.yml
  modules/openy_features/openy_datalayer/openy_datalayer.info.yml
  modules/openy_features/openy_editor/openy_editor.info.yml
  modules/openy_features/openy_media/modules/openy_media_document/openy_media_document.info.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.info.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/openy_media_local_video.info.yml
  modules/openy_features/openy_media/modules/openy_media_video/openy_media_video.info.yml
  modules/openy_features/openy_menu/modules/openy_menu_footer/openy_menu_footer.info.yml
  modules/openy_features/openy_menu/modules/openy_menu_main/openy_menu_main.info.yml
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.info.yml
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.info.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_code_block/openy_prgf_code_block.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_news/openy_prgf_featured_news.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_branch/openy_prgf_news_branch.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_camp/openy_prgf_news_camp.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_latest/openy_prgf_news_latest.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_news_listing/openy_prgf_news_listing.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/openy_txnm_news_category.info.yml
  modules/openy_features/openy_user/openy_user.info.yml
Labels: PR: Code Reviewed

#1214 [OPENY-124] Temporary hide OpenY Components tab on modules page
  modules/custom/openy_system/openy_system.links.task.yml
Labels: PR: Code Reviewed

#1198 [OPENY-111] Provide Leaflet maps support
  modules/custom/openy_map/config/install/openy_map.settings.yml
  modules/custom/openy_map/img/other/map_icon_red.png
  modules/custom/openy_map/img/other/map_icon_red_x2.png
  modules/custom/openy_map/js/map.js
  modules/custom/openy_map/openy_map.install
  modules/custom/openy_map/openy_map.libraries.yml
  modules/custom/openy_map/openy_map.module
  modules/custom/openy_map/src/Element/OpenYMap.php
  modules/custom/openy_map/src/Form/SettingsForm.php
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_branch.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_branch.scss
Labels: PR: Code Reviewed, PR: Tested

#1222 Schedules menu
  modules/custom/openy_gxp/src/Form/ImportForm.php
  modules/openy_features/openy_demo_content/modules/openy_demo_menu/modules/openy_demo_menu_main/config/install/migrate_plus.migration.menu_link_main.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nclass/config/install/migrate_plus.migration.node_activity.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nclass/config/install/migrate_plus.migration.node_class_02.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/openy_demo_nlanding.module
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.node_session_04.yml
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css.map
  themes/openy_themes/openy_rose/scss/base/_mixins.scss
Labels: PR: DO NOT MERGE

#1161 [OPENY-10] Installation UI improvements
  assets/installation-profile-ui.css
  assets/installation-profile-ui.js
  config/optional/easy_breadcrumb.settings.yml
  docs/Development/InstallationWithDrush.md
  modules/custom/location_finder/location_finder.info.yml
  modules/custom/openy_migrate/src/Importer.php
  modules/custom/openy_migrate/src/ImporterInterface.php
  modules/openy_features/openy_demo_content/modules/openy_demo_nalert/openy_demo_nalert.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nblog/openy_demo_nblog.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/openy_demo_nbranch.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/openy_demo_ncamp.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/openy_demo_nnews.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsocial_post/openy_demo_nsocial_post.info.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  openy.info.yml
  openy.install
  openy.installation_types.yml
  openy.libraries.yml
  openy.packages.yml
  openy.profile
  src/Form/ConfigureProfileForm.php
  src/Form/ContentSelectForm.php
  src/Form/ThirdPartyServicesForm.php
  themes/openy_themes/openy_rose/config/optional/block.block.openy_rose_fmenu_center.yml
  themes/openy_themes/openy_rose/config/optional/block.block.openy_rose_fmenu_left.yml
  themes/openy_themes/openy_rose/config/optional/block.block.openy_rose_fmenu_right.yml
Labels: PR: Needs Work

#1249 Improve upgrade experience
  modules/custom/openy_repeat/src/OpenyRepeatServiceProvider.php
Labels: Level: Middle, Severity: Important, Status: Needs review, Type: Bug

#1247 [YGBW-320] Fix duplicate sessions on PEF Schedules page
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Code Reviewed, PR: Needs Testing, Severity: Important, Type: Bug

#1250 Fix PEF category sorting (use "natural order" algorithm)
  modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
Labels: PR: Needs Review, PR: Needs Testing, Severity: Minor, Type: Enhancement

#1240 Fix incorrect links for Repeat Schedules
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--table.html.twig
  openy.info.yml
Labels: PR: Code Reviewed, PR: Tested, Type: Bug

#1258 [OPENY-138] Fix install error with moderation_state
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/openy_demo_nlanding.module
Labels: PR: Code Reviewed, PR: Tested, Type: Bug

#1253 [OPENY-137] 3rd party services configuration form updates
  openy.info.yml
  openy.profile
  src/Form/ThirdPartyServicesForm.php
Labels: PR: Code Reviewed, PR: Tested
