Repository ymcatwincities/openy, pull requests merged in 2018-09, with the labels that each got.

#1261 [OPENY-140] Fix membership calculator google map errors
  modules/custom/openy_map/js/map.js
Labels: PR: Code Reviewed, PR: Needs Testing, Type: Bug

#1252 [OPENY-131] Demo content cleaner - migrations data and configs
  modules/custom/openy_daxko2/config/install/migrate_plus.migration.daxko_categories_import.yml
  modules/custom/openy_daxko2/config/install/migrate_plus.migration.daxko_offerings_import.yml
  modules/custom/openy_gxp/migrations/migration.gxp_offerings_import.yml
  modules/custom/openy_system/openy_system.module
  modules/custom/openy_system/openy_system.services.yml
  modules/custom/openy_system/src/OpenyModulesManager.php
  modules/openy_features/openy_demo_content/modules/openy_demo_bamenities/config/install/migrate_plus.migration.block_content_amenities_block.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bamenities/config/install/migrate_plus.migration_group.openy_demo_bamenities.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bfooter/config/install/migrate_plus.migration.block_content_footer.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bfooter/config/install/migrate_plus.migration_group.openy_demo_fblock.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bmicrosites_menu/config/install/migrate_plus.migration.block_content_microsites_menu.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bmicrosites_menu/config/install/migrate_plus.migration_group.openy_demo_mblock.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bsimple/config/install/migrate_plus.migration.block_content_simple_block.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bsimple/config/install/migrate_plus.migration_group.openy_demo_fsimple.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nalert/config/install/migrate_plus.migration.node_alert.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nblog/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nblog/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nblog/config/install/migrate_plus.migration.node_blog.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.node_branch.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.prgf_grid_columns.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.prgf_grid_content.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.node_blog_camp.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.node_camp.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncampaign/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncategory/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncategory/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.node_event.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nfacility/config/install/migrate_plus.migration.node_facility.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ninterstitial/config/install/migrate_plus.migration.node_interstitial_page.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.lp_file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.node_news.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tamenities/config/install/migrate_plus.migration.amenities_file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tamenities/config/install/migrate_plus.migration.taxonomy_term_amenities.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tarea/config/install/migrate_plus.migration.taxonomy_term_area.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_taxonomy/config/install/migrate_plus.migration_group.openy_demo_term.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_taxonomy/openy_demo_taxonomy.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tblog/config/install/migrate_plus.migration.taxonomy_term_blog_category.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tblog/openy_demo_tblog.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tcolor/config/install/migrate_plus.migration.taxonomy_term_color.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tcolor/openy_demo_tcolor.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tfacility/config/install/migrate_plus.migration.taxonomy_term_facility_type.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tfacility/openy_demo_tfacility.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tfitness/config/install/migrate_plus.migration.taxonomy_term_fitness_category.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tfitness/openy_demo_tfitness.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tnews/config/install/migrate_plus.migration.taxonomy_term_news_category.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_tnews/openy_demo_tnews.info.yml
  openy.info.yml
  openy.profile
Labels: PR: Code Reviewed, PR: Tested

#1255 Issues #1254
  modules/custom/openy_map/src/Form/SettingsForm.php
Labels: PR: Code Reviewed, Severity: Normal

#1268 [OPENY-144] Interface for enabling/disabling packages in Admin Interface
  modules/custom/openy_system/openy_system.info.yml
  modules/custom/openy_system/openy_system.links.menu.yml
  modules/custom/openy_system/openy_system.links.task.yml
  modules/custom/openy_system/openy_system.routing.yml
  modules/custom/openy_system/src/Form/OpenyModulesListForm.php
  modules/custom/openy_system/src/Form/OpenyModulesUninstallConfirmForm.php
  modules/custom/openy_system/src/Form/OpenyModulesUninstallForm.php
  modules/openy_features/openy_demo_content/modules/openy_demo_webform/assets/yml/demo_form.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_webform/openy_demo_webform.install
  openy.packages.yml
Labels: PR: Code Reviewed, PR: Needs Work

#1276 [OPENY-130] Fix demo landing page content
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.node_landing_extended.yml
Labels: PR: Code Reviewed, PR: Tested

#1267 [OPENY-61] Complete installation type and drush
  modules/openy_features/openy_block/modules/openy_block_custom_simple/openy_block_custom_simple.info.yml
  modules/openy_features/openy_block/modules/openy_block_flexible_content/config/install/field.field.block_content.flexible_content.field_node_ref.yml
  modules/openy_features/openy_block/modules/openy_block_flexible_content/openy_block_flexible_content.info.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_bfooter/config/install/migrate_plus.migration.block_content_footer.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_menu/modules/openy_demo_menu_footer/config/install/migrate_plus.migration.menu_link_footer.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.event_landing.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.lp_paragraph_event_posts_listing.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nevent/config/install/migrate_plus.migration.node_event.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nmbrshp/config/install/migrate_plus.migration.node_membership.yml
  openy.info.yml
  openy.installation_types.yml
  openy.packages.yml
  openy.profile
  src/Form/ConfigureProfileForm.php
Labels: PR: Code Reviewed, PR: Needs Testing

#1287 [OPENY-143] Fix googletranslate block error for carnation theme in st…
  modules/custom/openy_gtranslate/config/optional/block.block.openy_carnation_googletranslate.yml
  openy.install
  openy.profile
Labels: PR: Code Reviewed, PR: Tested

#1279 [OPENY-141] Add description and help text for packages
  openy.packages.yml
  src/Form/ConfigureProfileForm.php
Labels: PR: Code Reviewed, PR: Tested

#1290 [OPENY-135] Fix error when uninstalling `openy_media_local_video` module
  modules/custom/openy_system/src/OpenyModulesManager.php
  modules/openy_features/openy_media/modules/openy_media_document/openy_media_document.info.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.info.yml
  modules/openy_features/openy_media/modules/openy_media_video/openy_media_video.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1293 [OPENY-154] Fix latest news posts teasers style for lily theme
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.node_landing.yml
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--latest-blog-posts--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--latest-blog-posts-branch--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--latest-blog-posts-camp--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--latest-news-posts--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--latest-news-posts-branch--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--latest-news-posts-camp--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--listing-blog-posts--block.html.twig
  themes/openy_themes/openy_lily/templates/views/views-view-unformatted--taxonomy_term.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1265 [YGBW-283] Fix focal point issues for banner and small banner paragraphs
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/image.style.prgf_banner.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.install
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/config/install/core.entity_view_display.paragraph.small_banner.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/config/install/image.style.prgf_small_banner.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.install
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_paragraphs.scss
Labels: PR: Needs Review, PR: Needs Testing, Severity: Minor

#1246 OS-160: Carnation Navigation Bug
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/js/openy_carnation.js
  themes/openy_themes/openy_carnation/src/scss/modules/_menu.scss
Labels: Level: Middle, PR: Code Reviewed, PR: Needs Testing, Type: Bug

#1239 OS-150 Location page. Force selection on at least one location
  modules/custom/openy_repeat/css/locations.css
  modules/custom/openy_repeat/js/locations.js
Labels: Level: Middle, PR: Needs Testing, Severity: Important

#1291 [OPENY-142] Fix teasers on home page
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/core.entity_view_display.node.blog.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.install
  modules/openy_features/openy_node/modules/openy_node_news/config/install/core.entity_view_display.node.news.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.install
Labels: PR: Code Reviewed, PR: Needs Testing

#1301 [OPENY-155] Update profile selection installation step text
  src/Form/ConfigureProfileForm.php
Labels: PR: Code Reviewed, PR: Tested

#1296 [OPENY-153] Add confirmation dialog to packages uninstall form submit
  modules/custom/openy_system/js/openy_system.js
  modules/custom/openy_system/openy_system.libraries.yml
  modules/custom/openy_system/src/Form/OpenyModulesUninstallConfirmForm.php
  modules/custom/openy_system/src/OpenyModulesManager.php
Labels: PR: Needs Review, PR: Needs Testing
