Repository ymcatwincities/openy, pull requests merged in 2018-10, with the labels that each got.

#1318 [OPENY-160] Update dependencies for blocks to fix install error in UI
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_fmenu_center.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_fmenu_left.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_fmenu_right.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_main_menu.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_mainnavigation.yml
Labels: PR: Needs Review, PR: Needs Testing

#1280 [OPENY-144] & [OPENY-153] & [OPENY-158] Open Y admin menu updates
  modules/custom/openy_system/assets/css/menu.css
  modules/custom/openy_system/assets/images/icon-gear-inactive.png
  modules/custom/openy_system/assets/images/icon-gear.png
  modules/custom/openy_system/openy_system.libraries.yml
  modules/custom/openy_system/openy_system.links.menu.yml
  modules/custom/openy_system/openy_system.module
  modules/custom/openy_system/openy_system.permissions.yml
  modules/custom/openy_system/openy_system.routing.yml
  modules/custom/openy_system/src/Form/OpenyModulesListForm.php
  modules/custom/openy_system/src/Form/OpenyModulesUninstallConfirmForm.php
  modules/custom/openy_system/src/Form/OpenyModulesUninstallForm.php
  openy.install
  openy.packages.yml
  openy.profile
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_footercopyrightblock.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_footersocialblock.yml
Labels: PR: Code Reviewed, PR: Tested

#1334 PEF: fix IE compatibility issue
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/openy_repeat.libraries.yml
Labels: PR: Needs Review, PR: Needs Testing, Severity: Critical, Type: Bug

#1327 Denisbilchenko/1319
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--table.html.twig
Labels: PR: Code Reviewed, PR: Needs Testing

#1333 PEF: optimize performance
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--table.html.twig
Labels: PR: Code Reviewed

#1047 [OS-32] Multiple branch hours
  README.md
  modules/custom/openy_autocomplete_path/css/autocomplete.css
  modules/custom/openy_autocomplete_path/openy_autocomplete_path.libraries.yml
  modules/custom/openy_autocomplete_path/openy_autocomplete_path.module
  modules/custom/openy_autocomplete_path/src/EntityAutocompleteMatcher.php
  modules/custom/openy_hours_formatter/openy_hours_formatter.module
  modules/custom/openy_hours_formatter/src/Plugin/Field/FieldFormatter/CustomHoursToday.php
  modules/custom/openy_hours_formatter/templates/openy-hours-formatter.html.twig
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/field.storage.node.field_branch_hours.yml
  openy.install
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/modules/_branch.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css.map
  themes/openy_themes/openy_rose/scss/modules/_branch.scss
Labels: Level: Middle, PR: Needs Testing, Severity: Important, Type: Feature

#1354 [OPENY-176] Decouple camp and location finder paragraph
  modules/custom/openy_map/config/install/views.view.locations.yml
  modules/custom/openy_map/openy_map.info.yml
  modules/custom/openy_map/openy_map.install
  modules/openy_features/openy_prgf/modules/openy_prgf_loc_finder/openy_prgf_loc_finder.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1359 [OPENY-183] Fix membership calc buttons padding to aviod overlap with…
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_membership.scss
Labels: PR: Code Reviewed, PR: Tested
