Repository ymcatwincities/openy, pull requests merged in 2018-07, with the labels that each got.

#1138 [OPENY-72] Location finder paragraphs decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_loc_finder/openy_prgf_loc_finder.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_loc_finder/openy_prgf_loc_finder.install
Labels: PR: Code Reviewed, PR: Tested

#1139 [OPENY-72] Membership calculator paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_mbrshp_calc/openy_prgf_mbrshp_calc.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_mbrshp_calc/openy_prgf_mbrshp_calc.install
Labels: PR: Code Reviewed, PR: Tested

#1141 [OPENY-72] openy_addthis decoupling
  modules/custom/openy_addthis/openy_addthis.info.yml
  modules/custom/openy_addthis/openy_addthis.install
  modules/custom/openy_addthis/openy_addthis.routing.yml
  modules/custom/openy_addthis/openy_addthis.services.yml
  modules/custom/openy_addthis/src/Entity/AddThisUninstallValidator.php
  modules/custom/openy_addthis/src/Form/PrepareUninstallForm.php
Labels: PR: Code Reviewed, PR: Tested

#1142 [OPENY-70] Embeddable footer & header decoupling
  modules/custom/openy_hf/openy_hf.info.yml
  modules/custom/openy_hf/openy_hf.install
  modules/custom/openy_hf/openy_hf.module
Labels: PR: Code Reviewed, PR: Tested

#1146 [OPENY-76] Event paragraphs decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_event_latest/openy_prgf_event_latest.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_event_latest/openy_prgf_event_latest.install
  modules/openy_features/openy_prgf/modules/openy_prgf_event_listing/openy_prgf_event_listing.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_event_listing/openy_prgf_event_listing.install
Labels: PR: Code Reviewed, PR: Tested

#1147 [OPENY-73] Featured Highlights block decoupling
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/openy_block_featured_highlights.info.yml
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/openy_block_featured_highlights.install
Labels: PR: Code Reviewed, PR: Tested

#1148 [OPENY-74] Events CT decoupling
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.info.yml
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.install
Labels: PR: Code Reviewed, PR: Tested

#1144 [OPENY-69] Date block decoupling
  modules/openy_features/openy_block/modules/openy_block_date/openy_block_date.install
Labels: PR: Code Reviewed, PR: Tested

#1149 [OPENY-67] Membership CT decoupling
  modules/custom/openy_calc/openy_calc.info.yml
  modules/openy_features/openy_node/modules/openy_node_mbrshp/openy_node_mbrshp.info.yml
  modules/openy_features/openy_node/modules/openy_node_mbrshp/openy_node_mbrshp.install
  modules/openy_features/openy_prgf/modules/openy_prgf_mbrshp_calc/openy_prgf_mbrshp_calc.install
Labels: PR: Code Reviewed, PR: Tested

#1154 Fix symfony dom-crawler version
  composer.json
  composer.lock
Labels: PR: Needs Review, Severity: Critical, Type: Bug

#1118 Add entity reference selection plugins
  modules/custom/openy_er/README.md
  modules/custom/openy_er/openy_er.info.yml
  modules/custom/openy_er/openy_er.module
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/BlockSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/DefaultSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/NodeSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php
  openy.info.yml
  openy.install
Labels: PR: Needs Review

#1166 [OPENY-84] Schedule search form & list paragraphs decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_schedule_search/openy_prgf_schedule_search.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_schedule_search/openy_prgf_schedule_search.install
Labels: PR: Code Reviewed, PR: Tested

#1168 [OPENY-86] Program Registration (Daxko) paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_pgm_reg/openy_prgf_pgm_reg.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_pgm_reg/openy_prgf_pgm_reg.install
Labels: PR: Code Reviewed, PR: Tested

#1167 [OPENY-85] Group Schedules (GroupEx Pro) paragraph decoupling
  modules/openy_features/openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.install
Labels: PR: Code Reviewed, PR: Tested

#1150 [OPENY-66] Branch CT decoupling
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
Labels: PR: Code Reviewed, PR: Tested

#1151 [OPENY-68] Amenities & Color taxonomy decoupling
  modules/openy_features/openy_taxonomy/modules/openy_txnm_amenities/openy_txnm_amenities.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_amenities/openy_txnm_amenities.install
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/openy_txnm_color.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/openy_txnm_color.install
Labels: PR: Code Reviewed, PR: Tested

#1160 Updating node templates to render AddThis
  themes/openy_themes/openy_lily/templates/node/include/node--landing-page--one-column-full.html.twig
  themes/openy_themes/openy_lily/templates/node/node--program--full.html.twig
  themes/openy_themes/openy_lily/templates/node/node--program-subcategory--full.html.twig
  themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig
  themes/openy_themes/openy_rose/templates/node/node--program--full.html.twig
  themes/openy_themes/openy_rose/templates/node/node--program-subcategory--full.html.twig
Labels: PR: Code Reviewed, PR: Needs testing

#1169 [OPENY-107] OpenY Session instance decoupling
  composer.json
  composer.lock
  modules/custom/openy_addthis/src/Entity/AddThisUninstallValidator.php
  modules/custom/openy_branch_selector/openy_branch_selector.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1180 [OPENY-78] Decoupling Limited Time Offer paragraph
  modules/openy_features/openy_prgf/modules/openy_prgf_lto/openy_prgf_lto.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_lto/openy_prgf_lto.install
Labels: PR: Code Reviewed, PR: Tested

#1182 [OPENY-80] Update dependencies to scheduler module
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.info.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/openy_loc_facility.info.yml
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.info.yml
  modules/openy_features/openy_node/modules/openy_node_mbrshp/openy_node_mbrshp.info.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1185 [OPENY-83] Social post CT decoupling
  modules/openy_features/openy_demo_content/modules/openy_demo_nsocial_post/openy_demo_nsocial_post.info.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.info.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.install
Labels: PR: Code Reviewed, PR: Tested

#1181 [OPENY-79] Microsites Menu paragraph and Menu block decoupling
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.info.yml
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.install
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_microsites_menu/openy_prgf_microsites_menu.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_microsites_menu/openy_prgf_microsites_menu.install
Labels: PR: Code Reviewed, PR: Tested

#1175 [OPENY-87][OPENY-92] Session CT and SessionTime prgf decoupling
  modules/custom/openy_popups/openy_popups.info.yml
  modules/custom/openy_popups/src/Controller/PopupsController.php
  modules/custom/openy_popups/src/Form/ClassBranchesForm.php
  modules/custom/openy_popups/src/Plugin/Block/LocationPopupLink.php
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.install
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1179 [OPENY-77] Breadcrumbs config updates
  openy.install
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_breadcrumbs.yml
  themes/openy_themes/openy_rose/templates/block/block--openy-rose-breadcrumbs.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1176 [OPENY-91] Class CT decoupling
  modules/openy_features/openy_node/modules/openy_node_class/openy_node_class.info.yml
  modules/openy_features/openy_node/modules/openy_node_class/openy_node_class.install
Labels: PR: Code Reviewed, PR: Tested

#1191 [OPENY-109] Add OpenY Camp dependency for the OpenY Paragraph Camp Menu
  modules/openy_features/openy_prgf/modules/openy_prgf_camp_menu/openy_prgf_camp_menu.info.yml
Labels: PR: Code Reviewed

#1189 [OPENY-96] OpenY Font decoupling
  modules/custom/openy_font/openy_font.info.yml
Labels: PR: Code Reviewed

#1188 [OPENY-94] OpenY Popups decoupling
  modules/custom/openy_popups/openy_popups.install
Labels: PR: Code Reviewed, PR: Tested

#1190 [OPENY-102] Fix mapping menu routes
  modules/custom/openy_mappings/openy_mappings.links.menu.yml
Labels: PR: Code Reviewed, PR: Tested

#1192 [OPENY-97] OpenY Tour decoupling updates
  modules/custom/openy_tour/openy_tour.info.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/config/optional/tour.tour.openy-branch-add.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  modules/openy_features/openy_menu/openy_menu.info.yml
  modules/openy_features/openy_menu/openy_menu.install
  modules/openy_features/openy_node/config/optional/tour.tour.openy-landing-page-add.yml
  modules/openy_features/openy_node/config/optional/tour.tour.openy-node-add.yml
  modules/openy_features/openy_node/config/optional/tour.tour.openy-node-overview.yml
  modules/openy_features/openy_node/openy_node.info.yml
  modules/openy_features/openy_node/openy_node.install
  modules/openy_features/openy_taxonomy/openy_taxonomy.info.yml
  modules/openy_features/openy_taxonomy/openy_taxonomy.install
Labels: PR: Code Reviewed, PR: Tested

#1194 [OPENY-98] OpenY Rose theme configs decoupling
  openy.install
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_branding.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_content.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_fmenu_center.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_fmenu_left.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_fmenu_right.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_main_menu.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_mainnavigation.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_tabs.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_user_menu.yml
  themes/openy_themes/openy_rose/config/install/block.block.openy_rose_useraccountmenu.yml
  themes/openy_themes/openy_rose/templates/page/page--header.html.html.twig
  themes/openy_themes/openy_rose/templates/page/page.html.twig
Labels: PR: Code Reviewed, PR: Tested
