Repository ymcatwincities/openy, pull requests merged in 2019-03, with the labels that each got.

#1545 [Issue #1544]: Fixed composer.lock file
  composer.json
  composer.lock
  docs/Development/Composer.md
Labels: PR: Needs Review, PR: Needs Testing

#1521 Today hours
  modules/custom/openy_hours_formatter/js/luxon/luxon.js
  modules/custom/openy_hours_formatter/js/luxon/luxon.js.map
  modules/custom/openy_hours_formatter/js/luxon/luxon.min.js
  modules/custom/openy_hours_formatter/js/luxon/luxon.min.js.map
  modules/custom/openy_hours_formatter/js/openy_hours_formatter.js
  modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
  modules/custom/openy_hours_formatter/openy_hours_formatter.libraries.yml
  modules/custom/openy_hours_formatter/openy_hours_formatter.module
  modules/custom/openy_hours_formatter/src/Plugin/Field/FieldFormatter/CustomHoursToday.php
Labels: PR: DO NOT MERGE, PR: Needs Work

#1548 PEF: Make classname filter affect generated PDF
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/openy_repeat.libraries.yml
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Needs Review, PR: Needs Testing

#1549 PEF: Return checkbox theming
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
Labels: PR: Needs Review, PR: Needs Testing

#1550 PEF: Make landing pages with Schedule blocks indexable by Search API
  modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
Labels: PR: Needs Review

#1557 Remove unnecessary $install_state argument
  src/Form/TermsOfUseForm.php
Labels: PR: Code Reviewed

#1562 Lock versions of the patched modules
  composer.json
Labels: PR: Code Reviewed, PR: Tested

#1563 Lock versions of media_entity, critical for the upgrade path
  composer.json
Labels: PR: Code Reviewed, PR: Tested
