Repository ymcatwincities/openy, pull requests merged in 2019-12, with the labels that each got.

#1828 Hide prev page pager link on first page of activity finder result page.
  modules/custom/openy_activity_finder/templates/openy-activity-finder-program-search-page.html.twig
Labels: PR: Needs Review

#1839 Fixed expanded ages and days filters on activity finder loading.
  modules/custom/openy_activity_finder/templates/openy-activity-finder-program-search-page.html.twig
Labels: PR: Needs Review

#1829 Focal point is not saved for images existed before enabling the feature
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointEditForm.php
Labels: PR: Needs Review

#1830 [CIYMCA-112] Schedules: Error on filtering by category
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/js/repeat/src/repeat.js
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Needs Review, PR: Needs Testing

#1840 [CIYMCA-132] Make not show the icon if the email is empty
  themes/openy_themes/openy_carnation/templates/node/event/event-contact-info.html.twig
Labels: PR: Code Reviewed, PR: Needs Testing

#1841 Getting RepeatActualizeBatch class back (seems it's forgotten)
  modules/custom/openy_repeat/src/Batch/RepeatActualizeBatch.php
Labels: PR: Needs Review

#1842 [OYS-31] Make Alert slider accessible
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/AppFooter.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/AppHeader.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/components/FooterAlertItem/FooterAlertItem.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/components/HeaderAlertItem/HeaderAlertItem.js
Labels: PR: Needs Review, PR: Needs Testing

#1847 [OYS-35] Fix missing header image for program page at carnation theme
  themes/openy_themes/openy_carnation/templates/node/program/node--program--full.html.twig
Labels: PR: Needs Review, PR: Needs Testing

#1846 Carnation Accessibility tasks.
  modules/custom/openy_calc/js/openy_calc_submit.js
  modules/custom/openy_calc/openy_calc.module
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/js/openy_carnation_banner.js
  themes/openy_themes/openy_carnation/dist/js/openy_carnation_menu.js
  themes/openy_themes/openy_carnation/openy_carnation.info.yml
  themes/openy_themes/openy_carnation/openy_carnation.libraries.yml
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_gallery.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_headerbanner.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_membership.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_page.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_site-alert.scss
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_banner.scss
  themes/openy_themes/openy_carnation/templates/media/media--full.html.twig
  themes/openy_themes/openy_carnation/templates/menu/menu--main--primary-menu.html.twig
  themes/openy_themes/openy_carnation/templates/node/blog/node--blog--teaser.html.twig
  themes/openy_themes/openy_carnation/templates/node/include/header-default--camp.html.twig
  themes/openy_themes/openy_carnation/templates/node/include/header-default--program-subcategory.html.twig
  themes/openy_themes/openy_carnation/templates/node/include/header-default.html.twig
  themes/openy_themes/openy_carnation/templates/node/node--landing-page--full.html.twig
  themes/openy_themes/openy_carnation/templates/node/program/node--program--full.html.twig
  themes/openy_themes/openy_carnation/templates/openy_calc/openy-calc-form-header.html.twig
  themes/openy_themes/openy_carnation/templates/openy_calc/openy-calc-form-summary.html.twig
  themes/openy_themes/openy_carnation/templates/page/html.html.twig
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
  themes/openy_themes/openy_carnation/templates/user/page--user--login.html.twig
Labels: PR: Needs Review

#1843 [CIYMCA-139] Fix add to calendar link.
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/js/repeat/src/repeat.js
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--table.html.twig
Labels: PR: Code Reviewed, PR: Needs Testing

#1833 Fixed non-closing message in modal
  themes/openy_themes/openy_carnation/dist/js/openy_carnation.js
Labels: PR: Needs Review

#1853 [YGBWSLA-121] Add cookies enabled checking and delay between HB popup appearance
  modules/custom/openy_home_branch/js/hb-plugins/hb-loc-modal.js
  modules/custom/openy_home_branch/js/hb_cookies_storage.js
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocModal.php
Labels: PR: Code Reviewed, PR: Tested
