Repository ymcatwincities/openy, pull requests merged in 2019-06, with the labels that each got.

#1604 PEF: get rid of the time part in date query param
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Code Reviewed, PR: Tested

#1614 Fix broken links in openy_hf module
  modules/custom/openy_hf/openy_hf.module
  modules/custom/openy_hf/openy_hf.services.yml
  modules/custom/openy_hf/src/EventSubscriber/ResponseEventSubscriber.php
Labels: Level: Middle, PR: Code Reviewed, Severity: Important, Type: Bug

#1618 Email on branch page
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_branch.scss
  themes/openy_themes/openy_carnation/templates/node/branch/node--branch--full.html.twig
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/misc/_location.scss
  themes/openy_themes/openy_lily/templates/node/node--branch--full.html.twig
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_branch.scss
  themes/openy_themes/openy_rose/templates/node/node--branch--full.html.twig
Labels: PR: Needs Review, PR: Needs Testing
