Repository ymcatwincities/openy, pull requests merged in 2019-04, with the labels that each got.

#1565 Add update hook dependencies for making Upgrade path to 2.x possible
  openy.install
Labels: PR: Code Reviewed, PR: Tested

#1321 issue-1235 fixed methods calls in the child component
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--table.html.twig
Labels: PR: Needs Work, Type: Bug

#1571 Add extra checking if ids not empty.
  modules/custom/openy_session_instance/openy_session_instance.module
Labels: PR: Needs clarification

#1581 [YGBWCDA-56] Disable map scrolling on Location Page
  modules/custom/openy_map/js/map.js
Labels: PR: Needs Review, PR: Needs Testing, Severity: Minor, Type: Enhancement

#1580 [OPENY-290] Add bulk update actions for OpenY Upgrade log
  modules/custom/openy_upgrade_tool/config/install/views.view.openy_upgrade_dashboard.yml
  modules/custom/openy_upgrade_tool/config/optional/system.action.apply_active_version.yml
  modules/custom/openy_upgrade_tool/config/optional/system.action.apply_openy_version.yml
  modules/custom/openy_upgrade_tool/config/schema/openy_upgrade_tool.schema.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.install
  modules/custom/openy_upgrade_tool/src/Plugin/Action/ApplyCurrentActiveVersionAction.php
  modules/custom/openy_upgrade_tool/src/Plugin/Action/ApplyOpenyVersionAction.php
Labels: PR: Needs Review, PR: Needs Testing, PR: Needs Work
