Repository ymcatwincities/openy, pull requests merged in 2019-08, with the labels that each got.

#1672 [YGSSLA-64] Make Class/Activity/Category/Program nodes' cascade update procedures take moderation states into account
  modules/custom/openy_moderation_wrapper/src/EntityModerationStatus.php
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.module
  modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.module
  modules/openy_features/openy_node/modules/openy_node_class/openy_node_class.module
Labels: PR: DO NOT MERGE

#1674 [YGBWSLA-85] Fix PEF modal window paddings and margins
  modules/custom/openy_system/assets/css/modal.css
Labels: PR: Needs Review, PR: Needs Testing

#1680 [YGBWSLA-88] Fix for failed to load original object entity:node error after node deletion
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Code Reviewed, PR: Needs Review, PR: Needs Testing

#1682 [YGBWHB-14] Alerts Refactoring + new custom hook
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_form_display.node.alert.default.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.default.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.node_alert_footer.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.node_alert_header.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/field.field.node.alert.field_alert_belongs.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.api.php
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php
Labels: PR: Code Reviewed, PR: Needs Testing, Type: Enhancement

#1683 [OYS-17] Add field_header_content to program
  docs/Content structure/Content Types/Program.md
  modules/openy_features/openy_node/modules/openy_node_program/config/install/core.entity_form_display.node.program.default.yml
  modules/openy_features/openy_node/modules/openy_node_program/config/install/core.entity_view_display.node.program.default.yml
  modules/openy_features/openy_node/modules/openy_node_program/config/install/core.entity_view_display.node.program.full.yml
  modules/openy_features/openy_node/modules/openy_node_program/config/install/core.entity_view_display.node.program.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_program/config/install/field.field.node.program.field_header_content.yml
  modules/openy_features/openy_node/modules/openy_node_program/openy_node_program.install
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_program.scss
  themes/openy_themes/openy_lily/sass/paragraphs/_paragraphs.scss
  themes/openy_themes/openy_lily/templates/node/node--program--full.html.twig
  themes/openy_themes/openy_rose/Gemfile
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_program.scss
  themes/openy_themes/openy_rose/templates/node/node--program--full.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1699 Little refactor of config according to DI
  modules/custom/openy_activity_finder/src/Form/SettingsForm.php
Labels: PR: Needs Review

#1687 Home Branch
  modules/custom/openy_home_branch/README.md
  modules/custom/openy_home_branch/css/hb-checkbox.css
  modules/custom/openy_home_branch/css/hb-loc-selector-branch-page.css
  modules/custom/openy_home_branch/css/hb_loc_modal.css
  modules/custom/openy_home_branch/css/hb_location_finder.css
  modules/custom/openy_home_branch/js/hb-plugin-base.js
  modules/custom/openy_home_branch/js/hb-plugins/hb-activity-finder-location.js
  modules/custom/openy_home_branch/js/hb-plugins/hb-loc-modal.js
  modules/custom/openy_home_branch/js/hb-plugins/hb-loc-selector-branch-page.js
  modules/custom/openy_home_branch/js/hb-plugins/hb-location-finder.js
  modules/custom/openy_home_branch/js/hb-plugins/hb-menu-selector.js
  modules/custom/openy_home_branch/js/hb-plugins/hb-pef-location.js
  modules/custom/openy_home_branch/js/hb_cookies_storage.js
  modules/custom/openy_home_branch/modules/openy_hb_override_example/js/hb-loc-finder-override.js
  modules/custom/openy_home_branch/modules/openy_hb_override_example/openy_hb_override_example.info.yml
  modules/custom/openy_home_branch/modules/openy_hb_override_example/openy_hb_override_example.libraries.yml
  modules/custom/openy_home_branch/modules/openy_hb_override_example/openy_hb_override_example.module
  modules/custom/openy_home_branch/openy_home_branch.info.yml
  modules/custom/openy_home_branch/openy_home_branch.install
  modules/custom/openy_home_branch/openy_home_branch.libraries.yml
  modules/custom/openy_home_branch/openy_home_branch.module
  modules/custom/openy_home_branch/openy_home_branch.services.yml
  modules/custom/openy_home_branch/src/Annotation/HomeBranchLibrary.php
  modules/custom/openy_home_branch/src/HomeBranchLibraryBase.php
  modules/custom/openy_home_branch/src/HomeBranchLibraryInterface.php
  modules/custom/openy_home_branch/src/HomeBranchLibraryManager.php
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocModal.php
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocSelectorActivityFinder.php
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocSelectorBranchPage.php
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocSelectorPEF.php
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocationFinder.php
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBMenuSelector.php
  themes/openy_themes/openy_carnation/openy_carnation.libraries.yml
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/css/hb-location-finder-override.css
  themes/openy_themes/openy_carnation/src/js/hb-loc-selector-branch-page-override.js
  themes/openy_themes/openy_carnation/src/js/hb-location-finder-override.js
  themes/openy_themes/openy_carnation/src/js/hb-menu-selector-override.js
  themes/openy_themes/openy_carnation/templates/field/field--paragraph--field-prgf-repeat-lschedules-prf.html.twig
  themes/openy_themes/openy_carnation/templates/menu/mobile/menu--account--top-menu.html.twig
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/openy_lily.libraries.yml
  themes/openy_themes/openy_lily/openy_lily.theme
  themes/openy_themes/openy_lily/sass/modules/_home_branch.scss
  themes/openy_themes/openy_lily/sass/style.scss
  themes/openy_themes/openy_lily/scripts/hb-loc-selector-branch-page-override.js
Labels: PR: Code Reviewed, PR: Needs Testing, Type: Docs, Type: Feature

#1709 [OS-509]: Refactor Date format in events
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.module
  modules/openy_features/openy_node/modules/openy_node_event/templates/event-date-info.html.twig
Labels: Severity: Minor, Type: Bug

#1701 [YGBWHB-37] Show spinner instead locations in PEF when HB selected
  modules/custom/openy_home_branch/README.md
  modules/custom/openy_home_branch/js/hb-plugins/hb-pef-location.js
  modules/custom/openy_home_branch/openy_home_branch.libraries.yml
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocSelectorPEF.php
Labels: PR: Needs Review, PR: Needs Testing, Type: Enhancement

#1710 Update ActivityStep.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/components/ActivityStep.vue
Labels: PR: Needs Review

#1702 Updated BTButton package
  composer.json
Labels: PR: Needs Review

#1714 Fixed package name
  modules/custom/openy_pef_gxp_sync/openy_pef_gxp_sync.info.yml
Labels: PR: Needs Review

#1717 [OYS-20]: WYSIWYG Custom Font Sizes
  composer.json
  modules/openy_features/openy_editor/config/install/editor.editor.full_html.yml
  modules/openy_features/openy_editor/openy_editor.info.yml
  modules/openy_features/openy_editor/openy_editor.install
Labels: PR: Code Reviewed, PR: Tested
