Repository ymcatwincities/openy, pull requests merged in 2019-01, with the labels that each got.

#1422 Optimize Addthis library loading
  modules/custom/openy_addthis/js/addthis.js
Labels: PR: Code Reviewed, PR: Needs Testing

#1391 [OPENY-168] PEF content changes reacting
  modules/custom/openy_repeat/modules/openy_repeat_nodes/openy_repeat_nodes.info.yml
  modules/custom/openy_repeat/modules/openy_repeat_nodes/openy_repeat_nodes.module
  modules/custom/openy_repeat/src/Batch/RepeatActualizeBatch.php
  modules/custom/openy_repeat/src/RepeatManager.php
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/openy_prgf_repeat_schedules.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules_loc/openy_prgf_repeat_schedules_loc.info.yml
Labels: PR: Code Reviewed, PR: Tested

#1425 [OPENY-240] Fixed styles of Limited Time Offer paragraph
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/css/vendor/bootstrap/bootstrap.css.map
  themes/openy_themes/openy_rose/scss/paragraphs/_lto.scss
Labels: Level: Middle, PR: Needs Review, PR: Needs Testing, Severity: Normal, Status: Needs review, Type: Bug

#1413 [OPENY-193] Daxko and OpenY Calc modules decoupling
  modules/custom/daxko/README.md
  modules/custom/daxko/daxko.info.yml
  modules/custom/daxko/daxko.services.yml
  modules/custom/daxko/src/DataWrapperBase.php
  modules/custom/daxko/src/DataWrapperInterface.php
  modules/custom/daxko/src/DaxkoDataWrapper.php
  modules/custom/daxko/src/DummyDataWrapper.php
  modules/custom/openy_calc/README.md
  modules/custom/openy_calc/openy_calc.info.yml
  modules/custom/openy_calc/openy_calc.services.yml
  modules/custom/openy_calc/src/Form/CalcBlockForm.php
Labels: PR: Code Reviewed, PR: Tested

#1417 [YGTC][BACKPORT] Introduce openy_theme_override module as part of Socrates.
  modules/custom/openy_socrates/modules/openy_autocomplete_path/css/autocomplete.css
  modules/custom/openy_socrates/modules/openy_autocomplete_path/openy_autocomplete_path.info.yml
  modules/custom/openy_socrates/modules/openy_autocomplete_path/openy_autocomplete_path.libraries.yml
  modules/custom/openy_socrates/modules/openy_autocomplete_path/openy_autocomplete_path.module
  modules/custom/openy_socrates/modules/openy_autocomplete_path/openy_autocomplete_path.services.yml
  modules/custom/openy_socrates/modules/openy_autocomplete_path/src/Controller/EntityAutocompleteController.php
  modules/custom/openy_socrates/modules/openy_autocomplete_path/src/EntityAutocompleteMatcher.php
  modules/custom/openy_socrates/modules/openy_autocomplete_path/src/Routing/AutocompleteRouteSubscriber.php
  modules/custom/openy_socrates/modules/openy_theme_override/openy_theme_override.info.yml
  modules/custom/openy_socrates/modules/openy_theme_override/openy_theme_override.module
  modules/custom/openy_socrates/modules/openy_theme_override/themes/README.md
  modules/custom/openy_socrates/modules/openy_theme_override/themes/openy_carnation/templates/.gitkeep
  modules/custom/openy_socrates/modules/openy_theme_override/themes/openy_lily/.gitkeep
  modules/custom/openy_socrates/modules/openy_theme_override/themes/openy_rose/.gitkeep
Labels: PR: Needs Review, PR: Needs Testing, Type: Feature

#1431 [ISSUE-1428]: Breadcrumbs are cut off on location finder in Carnation
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy_node_alert.js
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/component/_breadcrumbs.scss
Labels: PR: Code Reviewed, PR: Needs Testing

#1430 [OPENY-224] Remove excluded categories from PEF schedule filter
  modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
Labels: PR: Code Reviewed, PR: Tested

#1436 [OPENY-240] Breadcrumbs aren't visible
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/scss/paragraphs/_lto.scss
Labels: PR: Code Reviewed, PR: Tested

#1442 Openy 1429 grid content component in carnation
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--grid-content--default.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1324 PEF: class name filter
  RoboFile.php
  composer.json
  composer.lock
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/openy_repeat.libraries.yml
  modules/custom/openy_repeat/openy_repeat.module
  modules/custom/openy_repeat/src/Plugin/Block/RepeatSchedulesBlock.php
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/core.entity_form_display.paragraph.repeat_schedules.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/core.entity_view_display.paragraph.repeat_schedules.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_repeat_schedule_filt.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.field.paragraph.repeat_schedules.field_prgf_rs_pdf_only_view.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/config/install/field.storage.paragraph.field_prgf_repeat_schedule_filt.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/openy_prgf_repeat_schedules.install
  modules/openy_features/openy_prgf/modules/openy_prgf_repeat_schedules/openy_prgf_repeat_schedules.post_update.php
Labels: PR: Code Reviewed, PR: Tested

#1449 [OPENY-244] Change background image to the installation process
  themes/openy_themes/openy_admin/css/install-page.css
  themes/openy_themes/openy_admin/images/installation-background.png
  themes/openy_themes/openy_admin/images/y_abstract.png
Labels: PR: Needs Review, Severity: Normal, Status: Needs review, Type: Feature

#1454 Issue #1453: Schedules: IE padding issue
  modules/custom/openy_repeat/css/repeat.css
Labels: PR: Code Reviewed, PR: Tested

#1450 [OPENY-246] Backport PDF Schedules bug fix
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Code Reviewed, PR: Tested

#1457 Update Drupal to 8.6.7
  composer.json
  composer.lock
Labels: PR: Code Reviewed, PR: Tested

#1458 Remove obsolete code, disable debugging
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy_node_alert.js
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.libraries.yml
Labels: Type: Bug

#1460 [OPENY-247] Fix styles on the Program classes, the Location page, the Admin menu, etc.
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/scss/modules/_class.scss
  themes/openy_themes/openy_rose/scss/modules/_header.scss
  themes/openy_themes/openy_rose/scss/modules/_membership.scss
  themes/openy_themes/openy_rose/scss/modules/_program.scss
  themes/openy_themes/openy_rose/scss/paragraphs/_lto.scss
Labels: PR: Code Reviewed, PR: Tested

#1463 HotFix broken panelizer dependency
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.default.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.node_alert_footer.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.node_alert_header.yml
Labels: Level: Advanced, PR: Tested, Severity: Critical, Type: Bug

#1464 [OPENY-245] Fix inline tutorial videos
  modules/openy_features/openy_demo_content/modules/openy_demo_ahb/config/install/migrate_plus.migration.openy_demo_entity_ahb.yml
Labels: PR: Code Reviewed, PR: Tested

#1470 [OPENY-249] Update year in the footer to 2019
  modules/openy_features/openy_demo_content/modules/openy_demo_bfooter/config/install/migrate_plus.migration.block_content_footer.yml
Labels: PR: Needs Review, Status: Needs review

#1469 [OPENY-256] Fix placeholder error in template for schedules filter
  modules/custom/openy_schedules/templates/openy-schedules-subcategory-filters.html.twig
Labels: PR: Code Reviewed, PR: Tested

#1411 Skip moderation state checking if bundle not support content moderation
  modules/custom/openy_moderation_wrapper/src/EntityModerationStatus.php
Labels: PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Enhancement

#1415 [OPENY-229] Hide /node page
  modules/openy_features/openy_node/openy_node.info.yml
  modules/openy_features/openy_node/openy_node.install
  modules/openy_features/openy_node/openy_node.module
  openy.install
  openy.profile
Labels: PR: Code Reviewed, PR: Tested

#1471 [OPENY-255] Update demo content for the Give page
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.openy_demo_lp_paragraph_featured_content.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.openy_demo_node_landing.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.openy_demo_node_landing_extended.yml
Labels: PR: Needs Review

#1466 [OPENY-227] Upgrade tool improvements
  modules/custom/advanced_help_block/src/Form/AdvancedHelpBlockDeleteForm.php
  modules/custom/openy_upgrade_tool/README.md
  modules/custom/openy_upgrade_tool/config/install/core.entity_form_display.logger_entity.openy_config_upgrade_logs.default.yml
  modules/custom/openy_upgrade_tool/config/install/core.entity_view_display.logger_entity.openy_config_upgrade_logs.default.yml
  modules/custom/openy_upgrade_tool/config/install/field.field.logger_entity.openy_config_upgrade_logs.field_config_path.yml
  modules/custom/openy_upgrade_tool/config/install/field.field.logger_entity.openy_config_upgrade_logs.field_config_property.yml
  modules/custom/openy_upgrade_tool/config/install/field.storage.logger_entity.field_config_path.yml
  modules/custom/openy_upgrade_tool/config/install/field.storage.logger_entity.field_config_property.yml
  modules/custom/openy_upgrade_tool/config/install/logger_entity.logger_entity_type.openy_config_upgrade_logs.yml
  modules/custom/openy_upgrade_tool/config/install/openy_upgrade_tool.settings.yml
  modules/custom/openy_upgrade_tool/config/install/views.view.openy_upgrade_dashboard.yml
  modules/custom/openy_upgrade_tool/config/schema/openy_upgrade_tool.schema.yml
  modules/custom/openy_upgrade_tool/css/dashboard.css
  modules/custom/openy_upgrade_tool/openy_upgrade_log.page.inc
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.info.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.install
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.libraries.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.links.action.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.links.menu.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.links.task.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.module
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.permissions.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.routing.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.services.yml
  modules/custom/openy_upgrade_tool/src/ConfigParamUpgradeTool.php
  modules/custom/openy_upgrade_tool/src/ConfigUpdater.php
  modules/custom/openy_upgrade_tool/src/Controller/LoggerConfigController.php
  modules/custom/openy_upgrade_tool/src/Controller/OpenyUpgradeLogController.php
  modules/custom/openy_upgrade_tool/src/Entity/OpenyUpgradeLog.php
  modules/custom/openy_upgrade_tool/src/Entity/OpenyUpgradeLogInterface.php
  modules/custom/openy_upgrade_tool/src/Entity/OpenyUpgradeLogViewsData.php
  modules/custom/openy_upgrade_tool/src/EntityTypeInfo.php
  modules/custom/openy_upgrade_tool/src/EventSubscriber/ConfigEventSubscriber.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogDeleteForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogDiff.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogManualMerge.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogRevisionDeleteForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogRevisionRevertForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogSettingsForm.php
  modules/custom/openy_upgrade_tool/src/OpenYUpgradeToolFeatureStorage.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogAccessControlHandler.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogHtmlRouteProvider.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogListBuilder.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManager.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManagerInterface.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogStorage.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogStorageInterface.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeToolCachedStorage.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeToolRevisionStorage.php
  modules/custom/openy_upgrade_tool/src/Routing/RouteSubscriber.php
  modules/custom/openy_upgrade_tool/templates/openy-upgrade-log.html.twig
  modules/openy_features/openy_demo_content/modules/openy_demo_ahb/config/install/migrate_plus.migration.entity_ahb.yml
  openy.info.yml
  openy.install
  openy.post_update.php
Labels: Level: Advanced, PR: Needs Review, PR: Needs Testing, Type: Enhancement

#1418 [OPENY-238] Add step install with Terms of Use
  config/optional/openy.terms_and_conditions.schema.yml
  modules/custom/openy_system/openy_system.links.menu.yml
  modules/custom/openy_system/openy_system.routing.yml
  modules/custom/openy_system/openy_system.services.yml
  modules/custom/openy_system/src/EventSubscriber/TermsSubscriber.php
  openy.install
  openy.profile
  src/Form/TermsOfUseForm.php
  themes/openy_themes/openy_admin/css/install-page.css
Labels: PR: Needs Work

#1476 [VAY-18]: Fixed Carnation grid column width
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_grid_col.scss
Labels: PR: Code Reviewed, PR: Needs Review

#1478 [OPENY-265] Fix styles of the Limited Time Offer paragraph
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/scss/paragraphs/_lto.scss
Labels: PR: Code Reviewed, PR: Needs Review

#1479 [OPENY-241] Update contribs
  composer.json
  openy.install
Labels: PR: Code Reviewed, PR: Needs Testing

#1489 [OPENY-273] Fix warning in console
  modules/custom/openy_repeat/js/repeat.js
Labels: PR: Code Reviewed, PR: Needs Testing

#1493 [OPENY-260] Fix background image alignment on the installation
  themes/openy_themes/openy_admin/css/install-page.css
Labels: PR: Needs Review

#1486 PEF: Use dynamic query in RepeatController and add tag for alter
  modules/custom/openy_repeat/openy_repeat.api.php
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: Level: Middle, PR: Needs Review, PR: Needs Testing, Type: Enhancement

#1494 Updated font color
  themes/openy_themes/openy_carnation/README.md
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_1c.scss
Labels: Status: Needs review
