Repository ymcatwincities/openy, pull requests merged in 2019-07, with the labels that each got.

#1632 [OYS-12] Update header logo image paddings for Lily
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/misc/_header.scss
Labels: PR: DO NOT MERGE, PR: Needs Review, PR: Needs Testing, PR: Needs Work

#1652 [YGBWSLA-71] Fix type hinting for batch context in upgrade tool
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManager.php
Labels: PR: Needs Review

#1651 [YGBWSLA-71] Fix wrong config dir in activity_finder
  modules/custom/openy_activity_finder/config/optional/search_api.index.default.yml
  modules/custom/openy_activity_finder/openy_activity_finder.install
Labels: PR: DO NOT MERGE, PR: Needs Review

#1653 [YGBWSLA-71] Check config existing before import
  modules/custom/openy_activity_finder/openy_activity_finder.install
Labels: PR: Needs Review

#1654 [YGBWSLA-71] Fix for Notice: Undefined offset
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Needs Review

#1655 [YGBWSLA-71] Add sort value to ActivityFinder cache hash
  modules/custom/openy_activity_finder/src/Controller/ActivityFinderController.php
Labels: Status: Needs review

#1658 PEF: Show second button only on mobile
  modules/custom/openy_repeat/templates/openy-repeat-schedule-locations.html.twig
Labels: PR: Needs Review

#1663 Fix google translate select list option color
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_gtranslate.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_gtranslate.scss
Labels: PR: Needs Review, PR: Needs Testing

#1664 [YGBWSLA-79] Fix missing plus sign for ages without max age limit in activity finder popup
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Needs Review

#1657 [YGBWSLA-71] Restore session param in PEF class link
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Needs Review

#1665 [YGBWSLA-80] Allow other modules to alter the activity finder process results.
  modules/custom/openy_activity_finder/README.md
  modules/custom/openy_activity_finder/openy_activity_finder.api.php
  modules/custom/openy_activity_finder/openy_activity_finder.services.yml
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Needs Review, Type: Enhancement
