Repository ymcatwincities/openy, pull requests merged in 2019-09, with the labels that each got.

#1713 Fixed category filter on schedule dashboard.
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
Labels: PR: Needs Review

#1729 [YGBWSLA-90] Fix home branch plugin for ActivityFinder 2.0
  modules/custom/openy_home_branch/js/hb-plugins/hb-activity-finder-location.js
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocSelectorActivityFinder.php
Labels: PR: Needs Review, PR: Needs Testing

#1731 Activity Finder: Add exclude param to "View all programs" link
  modules/custom/openy_activity_finder/openy_af_vue_app/components/Homepage.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
Labels: PR: Needs Review, PR: Needs Testing

#1735 Expected ')' JS error in IE for the PEF and ActivityFinder 2.0
  modules/custom/openy_activity_finder/js/programs_search.js
  modules/custom/openy_repeat/js/repeat.js
Labels: PR: Needs Review, PR: Needs Testing, Severity: Important, Type: Bug

#1736 ActivityFinder: Expected ':' JS error fix for IE-11
  modules/custom/openy_activity_finder/js/programs_search.js
Labels: PR: Needs Review, PR: Needs Testing, Severity: Important, Type: Bug

#1737 ActivityFinder: Fix undefined argument in "View all programs" link
  modules/custom/openy_activity_finder/openy_af_vue_app/components/ActivityFinder.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/components/Homepage.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
Labels: PR: Needs Review, PR: Needs Testing, Severity: Normal

#1743 Notice: Only variables should be passed by reference
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Needs Review, Type: Bug
