Repository ymcatwincities/openy, pull requests merged in 2019-11, with the labels that each got.

#1774 ActivityFinder: Add search index config for SOLR backend.
  modules/custom/openy_activity_finder/config/install/openy_activity_finder.settings.yml
  modules/custom/openy_activity_finder/openy_activity_finder.install
  modules/custom/openy_activity_finder/src/Form/SettingsForm.php
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Code Reviewed, PR: Needs Testing

#1775 OS-571: Update group field alter for landing page
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.module
Labels: PR: Needs Review

#1777 Image Cropping and Focal point
  composer.json
  modules/custom/openy_focal_point/css/openy_focal_point.css
  modules/custom/openy_focal_point/js/openy_focal_point.js
  modules/custom/openy_focal_point/openy_focal_point.info.yml
  modules/custom/openy_focal_point/openy_focal_point.libraries.yml
  modules/custom/openy_focal_point/openy_focal_point.module
  modules/custom/openy_focal_point/openy_focal_point.routing.yml
  modules/custom/openy_focal_point/src/Ajax/RerenderThumbnailCommand.php
  modules/custom/openy_focal_point/src/Controller/OpenYFocalPointPreviewController.php
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointCropForm.php
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointEditForm.php
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointEntityReferenceBrowserWidget.php
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointImageWidget.php
  modules/custom/openy_focal_point/src/Plugin/ImageEffect/OpenYCropEffect.php
  modules/custom/openy_focal_point/src/Plugin/ImageEffect/OpenYFocalPointScaleAndCropImageEffect.php
  modules/custom/openy_focal_point/templates/openy-focal-point-preview.html.twig
  modules/openy_features/openy_media/modules/openy_media_image/config/install/core.entity_form_display.media.image.default.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/core.entity_view_display.media.image.icon.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.info.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/core.entity_form_display.paragraph.banner.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/crop.type.crop_960_600.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/image.style.prgf_banner.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.install
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/config/install/core.entity_form_display.paragraph.gallery.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/config/install/crop.type.crop_1920_700.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/config/install/image.style.prgf_gallery.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.install
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/config/install/core.entity_form_display.paragraph.small_banner.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/config/install/crop.type.crop_760_400.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/config/install/image.style.prgf_small_banner.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.install
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/core.entity_form_display.paragraph.teaser.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/crop.type.crop_260_220.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/image.style.prgf_teaser.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/openy_prgf_teaser.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/openy_prgf_teaser.install
  openy.install
Labels: PR: Needs Review

#1789 Updated Readme with known issues
  modules/custom/openy_pef_gxp_sync/README.md
Labels: PR: Needs Review

#1794 Issue #1793: Activity Finder error no search.
  modules/custom/openy_activity_finder/src/Form/SettingsForm.php
Labels: PR: Needs Review

#1798 Fixed groupex special charects in name
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: PR: Needs Review

#1806 Fixed html entity decode for js part of schedules at PEF
  modules/custom/openy_repeat/js/repeat.js
Labels: PR: Needs Review

#1796 Fix of banner at content area for Carnation.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/js/matchheight.js
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_banner.scss
Labels: PR: Needs Review

#1801 [OYS-31] Carnation mobile menu Accessibility Issue
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_mobile-menu.scss
  themes/openy_themes/openy_carnation/webpack.build.js
  themes/openy_themes/openy_carnation/webpack.dev.js
Labels: PR: Needs Review, PR: Needs Testing

#1815 Fixed bug with subcategories with the same title
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Needs Review

#1818 [CIYMCA-98] Add option to hide program and home branch block in af.
  modules/custom/openy_activity_finder/modules/openy_prgf_activity_finder/config/install/core.entity_form_display.paragraph.activity_finder.default.yml
  modules/custom/openy_activity_finder/modules/openy_prgf_activity_finder/config/install/core.entity_view_display.paragraph.activity_finder.default.yml
  modules/custom/openy_activity_finder/modules/openy_prgf_activity_finder/config/install/field.field.paragraph.activity_finder.field_prgf_hide_program_block.yml
  modules/custom/openy_activity_finder/modules/openy_prgf_activity_finder/config/install/field.storage.paragraph.field_prgf_hide_program_block.yml
  modules/custom/openy_activity_finder/modules/openy_prgf_activity_finder/openy_prgf_activity_finder.install
  modules/custom/openy_activity_finder/openy_af_vue_app/components/Homepage.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
Labels: PR: Code Reviewed, PR: Needs Testing

#1812 Backport: Fixed bug with showing equal name classes at separate rooms
  modules/custom/openy_repeat/src/Controller/RepeatController.php
  modules/custom/openy_repeat/templates/openy-repeat--pdf--table--activity.html.twig
Labels: PR: Needs Review

#1821 [MPR-15] - Add part of the day data to search index, enable filtering…
  modules/custom/openy_activity_finder/config/optional/search_api.index.default.yml
  modules/custom/openy_activity_finder/openy_activity_finder.install
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
  modules/custom/openy_activity_finder/src/Plugin/search_api/processor/PartsOfDay.php
Labels: PR: Needs Review, PR: Needs Testing

#1823 Perform the update if openy_carnation theme is active only
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.install
Labels: PR: Needs Review
