Repository ymcatwincities/openy, pull requests merged in 2019-02, with the labels that each got.

#1491 [OPENY-268] Fix styles on the location page
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/scss/modules/_location.scss
  themes/openy_themes/openy_rose/scss/paragraphs/_location_by_amenities.scss
  themes/openy_themes/openy_rose/scss/paragraphs/_lto.scss
Labels: PR: Code Reviewed

#1495 [OPENY-271] Cleanup of old hook_updates
  modules/custom/logger_entity/logger_entity.install
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.install
  modules/openy_features/openy_editor/openy_editor.info.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.install
  modules/openy_features/openy_location/modules/openy_loc_facility/openy_loc_facility.install
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
  modules/openy_features/openy_media/modules/openy_media_video/openy_media_video.install
  modules/openy_features/openy_menu/openy_menu.install
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.install
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.install
  modules/openy_features/openy_node/modules/openy_node_campaign/openy_node_campaign.install
  modules/openy_features/openy_node/modules/openy_node_category/openy_node_category.install
  modules/openy_features/openy_node/modules/openy_node_class/openy_node_class.install
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.install
  modules/openy_features/openy_node/modules/openy_node_mbrshp/openy_node_mbrshp.install
  modules/openy_features/openy_node/modules/openy_node_program/openy_node_program.install
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.install
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.install
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_branch/openy_prgf_blog_branch.install
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_camp/openy_prgf_blog_camp.install
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_latest/openy_prgf_blog_latest.install
  modules/openy_features/openy_prgf/modules/openy_prgf_blog_listing/openy_prgf_blog_listing.install
  modules/openy_features/openy_prgf/modules/openy_prgf_classes_listing/openy_prgf_classes_listing.install
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.install
  modules/openy_features/openy_prgf/modules/openy_prgf_grid_content/openy_prgf_grid_content.install
  modules/openy_features/openy_prgf/modules/openy_prgf_mbrshp_calc/openy_prgf_mbrshp_calc.install
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.install
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/openy_prgf_teaser.install
  modules/openy_features/openy_prgf/openy_prgf.install
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.install
  modules/openy_features/openy_taxonomy/openy_taxonomy.install
  modules/openy_features/openy_user/openy_user.install
  openy.info.yml
  openy.install
Labels: PR: Code Reviewed, PR: DO NOT MERGE, PR: Needs Testing

#1503 [OPENY-273] Fix warning in console when select other date
  modules/custom/openy_repeat/js/repeat.js
Labels: PR: Code Reviewed, PR: Tested

#1504 Openy 269
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
Labels: PR: DO NOT MERGE, Status: Needs review

#1497 [OPENY-270]: Terms of Use enhancement
  modules/custom/openy_system/openy_system.routing.yml
  modules/custom/openy_system/src/Controller/TermsOfUseController.php
  src/Form/TermsOfUseForm.php
  themes/openy_themes/openy_admin/css/install-page.css
Labels: PR: Code Reviewed, PR: Tested

#1505 [OPENY-278] Cleanup openy_node_session.install
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.install
Labels: PR: Code Reviewed, PR: Tested

#1507 [Openy 266]: Make T&C Agreement the first step of installation process
  modules/custom/openy_system/openy_system.links.menu.yml
  openy.profile
  src/Form/TermsOfUseForm.php
Labels: PR: Code Reviewed, PR: Tested

#1509 OS-272: Upping the limit for lengthy titled breadcrumbs
  themes/openy_themes/openy_carnation/openy_carnation.theme
Labels: PR: Needs Review

#1510 [OPENY-277]: Avoid using custom packages with drupal-library type
  composer.json
  composer.lock
Labels: PR: Code Reviewed, PR: Tested

#1511 [OPENY-267] Fix missing demo content paragraphs
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_nbranch_file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_nbranch_media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_prgf_3c_branch.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_prgf_gallery.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_prgf_grid_columns.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_prgf_grid_content.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_prgf_group_schedules.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nbranch/config/install/migrate_plus.migration.openy_demo_prgf_news_branch.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_ncamp_file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_ncamp_media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_node_camp.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_node_camp_news.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_prgf_camp_gallery.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_prgf_menu_camp.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_prgf_news_camp.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_ncamp/config/install/migrate_plus.migration.openy_demo_prgf_simple_camp.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/assets/images/10.jpg
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/assets/images/11.jpg
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/assets/images/12.jpg
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/assets/images/8.jpg
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/assets/images/9.jpg
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_lp_paragraph_news_posts_listing.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_lp_paragraph_news_small_banner.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_menu_link_footer_news.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_news_landing.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_nnews_file.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_nnews_media_image.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nnews/config/install/migrate_plus.migration.openy_demo_node_news.yml
Labels: PR: Code Reviewed, PR: Tested

#1506 [OPENY-272] [OPENY-196] Upgrade path tool issues fix
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.install
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.module
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.services.yml
  modules/custom/openy_upgrade_tool/src/Annotation/ConfigEventIgnore.php
  modules/custom/openy_upgrade_tool/src/ConfigEventIgnoreBase.php
  modules/custom/openy_upgrade_tool/src/ConfigEventIgnorePluginInterface.php
  modules/custom/openy_upgrade_tool/src/ConfigEventIgnorePluginManager.php
  modules/custom/openy_upgrade_tool/src/Controller/OpenyUpgradeLogController.php
  modules/custom/openy_upgrade_tool/src/EventSubscriber/ConfigEventSubscriber.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManager.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManagerInterface.php
  modules/custom/openy_upgrade_tool/src/Plugin/ConfigEventIgnore/Views.php
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/field.storage.block_content.field_block_content.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/simple_sitemap.bundle_settings.default.node.branch.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/config/install/simple_sitemap.bundle_settings.default.node.camp.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/config/install/simple_sitemap.bundle_settings.default.node.facility.yml
  modules/openy_features/openy_media/modules/openy_media_document/config/install/entity_browser.browser.documents_library.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/image.style.browser_thumbnail.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/image.style.thumbnail_for_preview.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/config/install/entity_browser.browser.local_video_library.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/config/install/entity_browser.browser.local_video_library_embed.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_blog/config/install/simple_sitemap.bundle_settings.default.node.blog.yml
  modules/openy_features/openy_node/modules/openy_node_category/config/install/simple_sitemap.bundle_settings.default.node.program_subcategory.yml
  modules/openy_features/openy_node/modules/openy_node_class/config/install/simple_sitemap.bundle_settings.default.node.class.yml
  modules/openy_features/openy_node/modules/openy_node_event/config/install/simple_sitemap.bundle_settings.default.node.event.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/simple_sitemap.bundle_settings.default.node.landing_page.yml
  modules/openy_features/openy_node/modules/openy_node_news/config/install/image.style.node_news_teaser.yml
  modules/openy_features/openy_node/modules/openy_node_news/config/install/simple_sitemap.bundle_settings.default.node.news.yml
  modules/openy_features/openy_node/modules/openy_node_program/config/install/simple_sitemap.bundle_settings.default.node.program.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_form_display.node.social_post.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_form_display.paragraph.social_list.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_view_display.node.social_post.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_view_display.node.social_post.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.field.node.social_post.field_link.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.field.node.social_post.field_post.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.field.node.social_post.field_posted.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.field.node.social_post.field_sp_image.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/node.type.social_post.yml
  modules/openy_features/openy_node/openy_node.module
  modules/openy_features/openy_prgf/modules/openy_prgf_mbrshp_calc/config/install/image.style.node_mbrshp_calc_preview.yml
  modules/openy_features/openy_user/config/install/user.role.anonymous.yml
  modules/openy_features/openy_user/config/install/user.role.authenticated.yml
  modules/openy_features/openy_user/src/Plugin/ConfigEventIgnore/Role.php
Labels: PR: Code Reviewed, PR: Tested

#1513 Activity Finder. Demo content
  modules/openy_features/openy_demo_content/modules/openy_demo_nclass/config/install/migrate_plus.migration.openy_demo_node_class_01.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nclass/config/install/migrate_plus.migration.openy_demo_node_class_02.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_01.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_02.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_03.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_04.yml
Labels: Level: Advanced, Type: Enhancement

#1518 [OPENY-283] Fix the Site information page submit
  modules/openy_features/openy_node/openy_node.module
Labels: PR: Code Reviewed, PR: Needs Testing

#1526 OPENY-1159: update css for membership calculator paddings.
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/modules/_paragraphs.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/css/styles.css.map
  themes/openy_themes/openy_rose/scss/modules/_paragraphs.scss
Labels: PR: Needs Review

#1527 [OPENY-284] Fix openy_node_alert updates.
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
Labels: PR: Needs Review, PR: Needs Testing

#1528 Change the name of the branch in the description of PR
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: Code Reviewed

#1531 Removed hardcoded HTTP auth from alerts JS
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/api.js
Labels: PR: Needs Review, PR: Needs Testing

#1532 Cherry pick commits from 1.x branch
  themes/openy_themes/openy_carnation/README.md
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_1c.scss
Labels: PR: Needs Review
