Repository ymcatwincities/openy, pull requests merged in 2020-12, with the labels that each got.

#2317 [ROY-23] Fix duplicate ID for alerts in the footer
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/index.js
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Bug

#2319 [ROY-37] Fix header.html for Rose theme
  themes/openy_themes/openy_rose/openy_rose.theme
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Type: Bug

#2318 Restore colorapi in composer.json
  composer.json
Labels: Level: Middle, PR: Tested, Type: Bug, dependencies

#2320 Enable colorapi enable before jquery_colorpicker_update_8200
  composer.json
  openy.install
Labels: Level: Advanced, Severity: Important, Type: Bug, dependencies

#2329 Fix embed icons generation
  modules/openy_features/openy_media/src/EmbedButtonIconHelper.php
Labels: Backporting, Level: Middle, Type: Bug

#2336 Alerts location fix
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.info.yml
  modules/openy_features/openy_location/openy_location.info.yml
  modules/openy_features/openy_mappings_feature/openy_mappings_feature.info.yml
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.info.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.info.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.info.yml
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.install
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.info.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_1c/openy_prgf_1c.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_2c/openy_prgf_2c.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_3c/openy_prgf_3c.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_4c/openy_prgf_4c.info.yml
Labels: Level: Advanced, Severity: Critical, Type: Bug, dependencies

#2337 9.x 2.x alerts fix
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.info.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.info.yml
  modules/openy_features/openy_location/openy_location.info.yml
  modules/openy_features/openy_mappings_feature/openy_mappings_feature.info.yml
  modules/openy_features/openy_node/modules/openy_node_activity/openy_node_activity.info.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.info.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.info.yml
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.install
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.info.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_1c/openy_prgf_1c.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_2c/openy_prgf_2c.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_3c/openy_prgf_3c.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_4c/openy_prgf_4c.info.yml
Labels: Backporting, Type: Bug

#2338 Libraries fork approved, now switching to official release
  composer.json
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Task, dependencies

#2321 Remove unused dependencies
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Task, dependencies

#2342 Updated Cachet installation instructions
  src/Form/UploadFontMessageForm.php
Labels: Level: Novice, Severity: Important, Type: Docs, Type: Task, Type: Tests, dependencies

#2328 Added EntityBrowserFormTrait (Activity Finder 4).
  modules/custom/openy_system/src/EntityBrowserFormTrait.php
Labels: Backporting, Five Jars, Level: Advanced, PR: Code Reviewed, Severity: Normal, Type: Task

#2355 Fix #2350 Wikimedia -> OpenStreetMaps
  modules/custom/openy_map/config/install/openy_map.settings.yml
  modules/custom/openy_map/openy_map.install
  modules/custom/openy_map/src/Form/SettingsForm.php
Labels: Level: Middle, PR: Tested, Severity: Normal, Type: Bug, dependencies
