Repository ymcatwincities/openy, pull requests merged in 2020-11, with the labels that each got.

#2270 1543 fix svg logo
  themes/openy_themes/openy_carnation/logo.svg
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
Labels: PR: Needs Review, PR: Needs Testing

#2276 Revert "Remove rabbit_hole dependencies"
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/rabbit_hole.behavior_settings.node_type_branch.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/config/install/rabbit_hole.behavior_settings.taxonomy_vocabulary_facility_type.yml
  modules/openy_features/openy_node/modules/openy_node_activity/config/install/rabbit_hole.behavior_settings.node_type_activity.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/rabbit_hole.behavior_settings.node_type_alert.yml
  modules/openy_features/openy_node/modules/openy_node_interstitial/config/install/rabbit_hole.behavior_settings.node_type_interstitial_page.yml
  modules/openy_features/openy_node/modules/openy_node_mbrshp/config/install/rabbit_hole.behavior_settings.node_type_membership.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/rabbit_hole.behavior_settings.node_type_session.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/config/install/rabbit_hole.behavior_settings.taxonomy_vocabulary_color.yml
Labels: Type: Task, dependencies

#2278 Fix broken configuration via override
  modules/openy_features/openy_media/config/override/media_directories.settings.yml
  modules/openy_features/openy_media/openy_media.install
Labels: Severity: Important, Type: Bug, Type: Task, dependencies

#2275 [INOYI-32] - fixed notice in db log "Undefined property: stdClass::$region in field_group_form_process" - applied contrib patch
  composer.json
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, PR: Tested, Type: Bug

#2280 Release of media_entity_video
  composer.json
Labels: PR: Code Reviewed, PR: Tested, Type: Task, dependencies

#2281 Fix Embed Button by downgrading dropzonejs to 2.1 version
  composer.json
Labels: Severity: Critical, Type: Bug, dependencies

#2285 Get supported ckeditor_bootstrap_buttons module version
  composer.json
Labels: Level: Novice, PR: Code Reviewed, PR: Tested, Type: Task, dependencies

#2283 Downgrade dropzonejs in order to get uploading working
  composer.json
Labels: PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug, dependencies

#2282 Update composer.json - use caret not tilde in version constraints due to better stability/best practices/semantic versioning
  composer.json
Labels: Level: Middle, Severity: Important, Type: Task, dependencies

#2286 Remove outlines rule from :focus pseudo-selectors in favor of box-shadow
  composer.json
  openy.info.yml
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/state/_state.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/state/_state.scss
Labels: IXM, PR: Needs Review

#2289 Link to Activity Finder v3 to be latest Drupal8/9 release
  composer.json
Labels: Backporting, Level: Middle, PR: Tested, Severity: Important, Type: Task, dependencies

#2290 Use caret instead of tilde in version strings
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Task, dependencies

#2287 Update upstream from 8.x to 9.x
  composer.json
  modules/openy_features/openy_block/modules/openy_block_date/config/install/field.field.block_content.date_block.field_content_date_between.yml
  modules/openy_features/openy_block/modules/openy_block_date/config/install/field.field.block_content.date_block.field_content_date_end.yml
  modules/openy_features/openy_block/modules/openy_block_date/openy_block_date.install
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/field.field.node.alert.field_alert_visibility_state.yml
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/reducers/init.js
  modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php
  modules/openy_features/openy_prgf/config/install/openy_prgf.settings.yml
  modules/openy_features/openy_prgf/openy_prgf.install
  modules/openy_features/openy_prgf/openy_prgf.module
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/config/install/field.field.taxonomy_term.blog_category.field_taxonomy_content.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.install
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/config/install/field.field.taxonomy_term.news_category.field_taxonomy_content.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/openy_txnm_news_category.install
  openy.info.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/logo.svg
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/state/_state.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/state/_state.scss
Labels: Backporting, Level: Advanced, PR: DO NOT MERGE, Type: Task

#2294 [YP2-18] Fix errors related to W3C validator.
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.openy_demo_lp_paragraph_simple.yml
  themes/openy_themes/openy_carnation/openy_carnation.libraries.yml
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--banner.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--grid-columns.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--small-banner.html.twig
Labels: PR: Needs Review, PR: Needs Testing

#2303 Removes outdated patch for the entity_browser
  composer.json
Labels: Severity: Minor, Status: Needs review, Type: Enhancement

#2306 Fix styles Coming Soon for Rose and Lily
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_branch.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_location.scss
Labels: Backporting, Level: Middle, Severity: Normal, Type: Bug, Type: Task

#2307 Mobile Branch Info for Lily, Rose, and Carnation
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_branch.scss
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_branch_contact_info.scss
  themes/openy_themes/openy_carnation/templates/block/block-branch-contacts-info.html.twig
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/misc/_camps-locations.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_branch.scss
  themes/openy_themes/openy_rose/templates/block/block-branch-contacts-info.html.twig
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Bug

#2308 [ROY-28] Fix FAQ field render
  modules/custom/openy_field_faq/templates/openy-faq-item.html.twig
  modules/openy_features/openy_prgf/modules/openy_prgf_faq/js/paragraph.js
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_faq.scss
  themes/openy_themes/openy_carnation/templates/modules/openy-faq-item.html.twig
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Bug

#2311 Backward compatibility for patched entity_embed
  composer.json
Labels: Level: Advanced, PR: Tested, Severity: Critical, Type: Bug, dependencies

#2312 [ROY-25] Fix half size image for Rose theme
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_landing.scss
  themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Bug

#2314 [ROY-36] Fix alerts in Pre-Footer of Program & Program Subcategory
  themes/openy_themes/openy_carnation/templates/node/program/node--program--full.html.twig
  themes/openy_themes/openy_carnation/templates/node/program/node--program-subcategory--full.html.twig
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Type: Bug
