Repository ymcatwincities/openy, pull requests merged in 2020-10, with the labels that each got.

#2216 Added check for empty blocks
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_lily/openy_lily.theme
  themes/openy_themes/openy_rose/openy_rose.theme
Labels: IXM, Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug

#2217 [openy/issues/2153][CR-60] Actualize openy_focal_point code
  modules/custom/openy_focal_point/css/openy_focal_point.css
  modules/custom/openy_focal_point/openy_focal_point.routing.yml
  modules/custom/openy_focal_point/src/Controller/OpenYFocalPointPreviewController.php
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointCropForm.php
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointEditForm.php
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointEntityReferenceBrowserWidget.php
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointImageWidget.php
Labels: Five Jars, PR: Needs Review, PR: Needs Testing

#2215 Trying to change failing Plugin Block field to view_field_view
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_form_display.paragraph.social_list.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_view_display.paragraph.social_list.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.field.paragraph.social_list.field_prgrf_sl_block.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.storage.paragraph.field_prgrf_sl_block.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.install
Labels: Level: Advanced, Severity: Critical, Type: Bug, Type: Experimental feature, dependencies

#2225 Fix embed icons generation
  modules/openy_features/openy_media/src/EmbedButtonIconHelper.php
Labels: Level: Middle, PR: Tested, Type: Bug

#2227 Allow webforms 5 for Drupal 8
  composer.json
Labels: Level: Advanced, Severity: Important, Type: Experimental feature, Type: Task

#2230 Add rerolled patch for drupal/plugin
  composer.json
Labels: Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug, Type: Task, dependencies

#2231 Revert "Trying to change failing Plugin Block field to view_field_view"
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_form_display.paragraph.social_list.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_view_display.paragraph.social_list.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.field.paragraph.social_list.field_prgrf_sl_block.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/field.storage.paragraph.field_prgrf_sl_block.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.install
Labels: Level: Advanced, PR: DO NOT MERGE, Type: Task

#2238 views_field_formatter release
  composer.json
Labels: Type: Task, dependencies

#2240 Pre-select paragraphs entities' checkboxes when cloning a node.
  modules/openy_features/openy_prgf/openy_prgf.services.yml
  modules/openy_features/openy_prgf/src/Config/OpenyParagraphOverrides.php
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2249 [2191] Display the field_content with any page layout value
  themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2255 Get beta version of custom_formatters
  composer.json
Labels: Level: Middle, Severity: Important, Type: Task, dependencies

#2257 Stable Contribs
  composer.json
Labels: Severity: Important, Type: Task, dependencies

#2258 Stable contribs for Major Release in November
  composer.json
Labels: PR: Code Reviewed, Type: Task, dependencies

#2254 Getting stable release of media_entity_image
  composer.json
Labels: PR: Code Reviewed, PR: Tested, Severity: Important, Type: Task, dependencies

#2261 Get latest css_editor
  composer.json
Labels: Level: Novice, PR: Code Reviewed, PR: Tested, Type: Task, dependencies

#2253 Stable verf module for 8.x
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Task, dependencies

#2260 Update safe contribs
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Type: Task, dependencies

#2264 update dismissed alerts filter
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/reducers/init.js
Labels: IXM, PR: Code Reviewed, PR: Tested, Type: Bug

#2251 [CR-80] Restrictions by bundle types for the Taxonomy fields…
  modules/openy_features/openy_block/modules/openy_block_date/config/install/field.field.block_content.date_block.field_content_date_between.yml
  modules/openy_features/openy_block/modules/openy_block_date/config/install/field.field.block_content.date_block.field_content_date_end.yml
  modules/openy_features/openy_block/modules/openy_block_date/openy_block_date.install
  modules/openy_features/openy_prgf/config/install/openy_prgf.settings.yml
  modules/openy_features/openy_prgf/openy_prgf.install
  modules/openy_features/openy_prgf/openy_prgf.module
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/config/install/field.field.taxonomy_term.blog_category.field_taxonomy_content.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_blog_category/openy_txnm_blog_category.install
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/config/install/field.field.taxonomy_term.news_category.field_taxonomy_content.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_news_category/openy_txnm_news_category.install
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, Type: Bug
