Repository ymcatwincities/openy, pull requests merged in 2020-02, with the labels that each got.

#1896 Remove Optimizely and Lndr modules
  composer.json
  composer.lock
  docs/Development/Optimizely.md
  docs/assets/optimizely_account_id.png
  docs/assets/optimizely_configuration_project_add_update.png
  docs/assets/optimizely_project_listing_page.png
  drupal-org.make
  modules/openy_features/openy_demo_content/modules/openy_demo_ahb/config/install/migrate_plus.migration.openy_demo_entity_ahb.yml
  openy.install
  openy.installation_types.yml
  openy.packages.yml
  src/Form/ConfigureProfileForm.php
  src/Form/ThirdPartyServicesForm.php
Labels: PR: Needs Review, PR: Needs Testing

#1859 Schedules aligning
  modules/custom/openy_repeat/css/repeat.css
Labels: PR: Code Reviewed, Severity: Minor, Type: Bug

#1850 YMCABW-19 Activity Finder: Added Home Branch functionality for Daxko backend
  modules/custom/openy_activity_finder/openy_af_vue_app/components/ActivityFinder.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/components/LocationStep.vue
  modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
  modules/custom/openy_activity_finder/src/Plugin/Block/ActivityFinderBlock.php
  modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
  modules/custom/openy_home_branch/js/hb-plugins/hb-activity-finder-location.js
  modules/custom/openy_home_branch/openy_home_branch.libraries.yml
  modules/custom/openy_home_branch/src/Plugin/HomeBranchLibrary/HBLocSelectorActivityFinder.php
Labels: PR: Needs Review

#1897 Revert "updated btbutton package in composer.json"
  composer.json
Labels: PR: Needs Review

#1900 OS-715 replaced render filter check with .isEmpty() check
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--banner.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--small-banner.html.twig
Labels: PR: Code Reviewed, Severity: Critical

#1901 Update captcha module 8.x-1.0-beta1 -> 8.x-1.0-beta4; update composer.lock
  composer.json
  composer.lock
Labels: PR: Code Reviewed, PR: Needs Testing

#1903 Fix versions in openy_system -> libraries
  modules/custom/openy_system/openy_system.libraries.yml
Labels: PR: Code Reviewed, PR: Needs Testing

#1904 Add hook_update dependencies to fix upgrade path errors
  openy.install
Labels: PR: Code Reviewed, PR: Needs Testing

#1908 Applied patch for Inline Editing
  composer.json
Labels: PR: Code Reviewed, Severity: Critical, Type: Bug

#1894 Media directories
  composer.json
  composer.lock
  modules/openy_features/openy_media/config/install/media_directories.settings.yml
  modules/openy_features/openy_media/config/install/taxonomy.vocabulary.media_folders.yml
  modules/openy_features/openy_media/css/browser.css
  modules/openy_features/openy_media/modules/openy_media_image/config/install/entity_browser.browser.images_library.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/entity_browser.browser.images_library_embed.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/views.view.images_library.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.info.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
  modules/openy_features/openy_media/openy_media.info.yml
  modules/openy_features/openy_media/openy_media.install
Labels: PR: Code Reviewed, PR: Tested

#1905 Carnation regression fixes after Drupal Core 8.8.
  modules/openy_features/openy_demo_content/modules/openy_demo_nlanding/config/install/migrate_plus.migration.openy_demo_node_landing.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/component/_breadcrumbs.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_microsites.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_program.scss
  themes/openy_themes/openy_carnation/templates/node/include/header-default--program-subcategory.html.twig
  themes/openy_themes/openy_carnation/templates/node/program/node--program-subcategory--full.html.twig
Labels: Level: Advanced, PR: Code Reviewed, PR: Tested

#1889 Analyics
  config/optional/openy.terms_and_conditions.schema.yml
  modules/custom/openy_analytics/openy_analytics.info.yml
  modules/custom/openy_analytics/openy_analytics.services.yml
  modules/custom/openy_analytics/src/AnalyticsCron.php
  modules/custom/openy_analytics/src/Form/SettingsForm.php
  modules/custom/openy_analytics/src/Plugin/Field/FieldFormatter/Json.php
  modules/custom/openy_system/openy_system.services.yml
  modules/custom/openy_system/src/EventSubscriber/TermsSubscriber.php
  openy.install
  src/Form/TermsOfUseForm.php
Labels: PR: Code Reviewed, PR: Needs Work

#1836 Egym iwatch
  modules/openy_features/openy_egym_iwatch/.gitignore
  modules/openy_features/openy_egym_iwatch/.sass-lint.yml
  modules/openy_features/openy_egym_iwatch/config/install/core.entity_form_display.paragraph.banner_fixed.default.yml
  modules/openy_features/openy_egym_iwatch/config/install/core.entity_view_display.media.image.prgf_banner_fixed.yml
  modules/openy_features/openy_egym_iwatch/config/install/core.entity_view_display.paragraph.banner_fixed.default.yml
  modules/openy_features/openy_egym_iwatch/config/install/core.entity_view_mode.media.prgf_banner_fixed.yml
  modules/openy_features/openy_egym_iwatch/config/install/crop.type.crop_1620_800.yml
  modules/openy_features/openy_egym_iwatch/config/install/field.field.paragraph.banner_fixed.field_prgf_headline.yml
  modules/openy_features/openy_egym_iwatch/config/install/field.field.paragraph.banner_fixed.field_prgf_image.yml
  modules/openy_features/openy_egym_iwatch/config/install/image.style.prgf_banner_fixed.yml
  modules/openy_features/openy_egym_iwatch/config/install/paragraphs.paragraphs_type.banner_fixed.yml
  modules/openy_features/openy_egym_iwatch/demo_images/1.png
  modules/openy_features/openy_egym_iwatch/demo_images/2.png
  modules/openy_features/openy_egym_iwatch/demo_images/3.png
  modules/openy_features/openy_egym_iwatch/demo_images/4.png
  modules/openy_features/openy_egym_iwatch/demo_images/5.png
  modules/openy_features/openy_egym_iwatch/demo_images/6.png
  modules/openy_features/openy_egym_iwatch/demo_images/HERO.png
  modules/openy_features/openy_egym_iwatch/demo_images/appstore.png
  modules/openy_features/openy_egym_iwatch/demo_images/clock.png
  modules/openy_features/openy_egym_iwatch/dist/css/openy_egym_iwatch.css
  modules/openy_features/openy_egym_iwatch/dist/main.js
  modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.features.yml
  modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.info.yml
  modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.install
  modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.libraries.yml
  modules/openy_features/openy_egym_iwatch/openy_egym_iwatch.module
  modules/openy_features/openy_egym_iwatch/package-lock.json
  modules/openy_features/openy_egym_iwatch/package.json
  modules/openy_features/openy_egym_iwatch/src/scss/openy_egym_iwatch.scss
  modules/openy_features/openy_egym_iwatch/templates/paragraph--banner-fixed.html.twig
  modules/openy_features/openy_egym_iwatch/templates/paragraph--grid-columns-egym.html.twig
  modules/openy_features/openy_egym_iwatch/templates/paragraph--grid-content-egym.html.twig
  modules/openy_features/openy_egym_iwatch/webpack-entry.js
  modules/openy_features/openy_egym_iwatch/webpack.build.js
  modules/openy_features/openy_egym_iwatch/webpack.common.js
  modules/openy_features/openy_egym_iwatch/webpack.dev.js
  openy.packages.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
  themes/openy_themes/openy_rose/openy_rose.theme
  themes/openy_themes/openy_rose/templates/page/html.html.twig
Labels: PR: Needs Review

#1909 OS-643 fixed styles for openy_egym_iwatch
  modules/openy_features/openy_egym_iwatch/dist/css/openy_egym_iwatch.css
  modules/openy_features/openy_egym_iwatch/package-lock.json
  modules/openy_features/openy_egym_iwatch/src/scss/openy_egym_iwatch.scss
Labels: PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Bug

#1906 Google Custom Search
  docs/Development/GoogleCustomSearchConfiguration.md
  modules/custom/openy_search/openy_google_search/config/install/core.entity_form_display.paragraph.google_search.default.yml
  modules/custom/openy_search/openy_google_search/config/install/core.entity_view_display.paragraph.google_search.default.yml
  modules/custom/openy_search/openy_google_search/config/install/openy_google_search.settings.yml
  modules/custom/openy_search/openy_google_search/config/install/paragraphs.paragraphs_type.google_search.yml
  modules/custom/openy_search/openy_google_search/js/google_search.js
  modules/custom/openy_search/openy_google_search/openy_google_search.info.yml
  modules/custom/openy_search/openy_google_search/openy_google_search.install
  modules/custom/openy_search/openy_google_search/openy_google_search.libraries.yml
  modules/custom/openy_search/openy_google_search/openy_google_search.links.menu.yml
  modules/custom/openy_search/openy_google_search/openy_google_search.module
  modules/custom/openy_search/openy_google_search/openy_google_search.routing.yml
  modules/custom/openy_search/openy_google_search/src/Form/SettingsForm.php
  modules/custom/openy_search/openy_google_search/templates/openy-google-search.html.twig
  modules/custom/openy_search/openy_search.info.yml
  modules/custom/openy_search/openy_search.services.yml
  modules/custom/openy_search/src/Config/OpenySearchOverrides.php
  openy.install
  openy.installation_types.yml
  openy.packages.yml
  src/Form/ThirdPartyServicesForm.php
  themes/openy_themes/openy_carnation/config/install/openy_carnation.settings.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_google_search.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
  themes/openy_themes/openy_lily/config/install/openy_lily.settings.yml
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/openy_lily.theme
  themes/openy_themes/openy_lily/sass/misc/_header.scss
  themes/openy_themes/openy_lily/sass/misc/_search.scss
  themes/openy_themes/openy_lily/sass/modules/_google_search.scss
  themes/openy_themes/openy_lily/sass/modules/_gtranslate.scss
  themes/openy_themes/openy_lily/sass/modules/_menu.scss
  themes/openy_themes/openy_lily/sass/style.scss
  themes/openy_themes/openy_lily/templates/include/sidebar-search-and-menu.html.twig
  themes/openy_themes/openy_lily/templates/include/site-search.html.twig
  themes/openy_themes/openy_lily/templates/menu/menu--account.html.twig
  themes/openy_themes/openy_lily/templates/page/page--header.html.html.twig
  themes/openy_themes/openy_lily/templates/page/page.html.twig
  themes/openy_themes/openy_rose/config/install/openy_rose.settings.yml
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/openy_rose.theme
  themes/openy_themes/openy_rose/scss/modules/_google_search.scss
  themes/openy_themes/openy_rose/scss/modules/_header.scss
  themes/openy_themes/openy_rose/scss/modules/_menu.scss
  themes/openy_themes/openy_rose/scss/styles.scss
  themes/openy_themes/openy_rose/templates/page/page--header.html.html.twig
  themes/openy_themes/openy_rose/templates/page/page.html.twig
  themes/openy_themes/openy_rose/templates/top-menu-search.html.twig
Labels: PR: Needs Review, PR: Needs Testing

#1910 Added core requirement.
  openy.info.yml
Labels: Level: Advanced, PR: Code Reviewed, Severity: Important, dependencies

#1911 Fix of The 'core_version_requirement' constraint (^8.8) requires the …
  openy.info.yml
Labels: PR: Needs Review

#1912 OS-706 create hook_cron for openy_analytics
  modules/custom/openy_analytics/openy_analytics.module
  modules/custom/openy_analytics/openy_analytics.services.yml
  modules/custom/openy_analytics/src/AnalyticsCron.php
Labels: PR: Needs Review

#1922 Make Leaflet tile patterns overrideable
  modules/custom/openy_map/config/install/openy_map.settings.yml
  modules/custom/openy_map/js/map.js
  modules/custom/openy_map/js/map/README.MD
  modules/custom/openy_map/js/map/src/map.js
  modules/custom/openy_map/js/map/webpack.config.js
  modules/custom/openy_map/openy_map.install
  modules/custom/openy_map/src/Element/OpenYMap.php
  modules/custom/openy_map/src/Form/SettingsForm.php
Labels: Five Jars, Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Experimental feature

#1915 [YGBWSLA-154] Fix ie11 bug with default js value for Home branch module
  modules/custom/openy_home_branch/js/hb-plugins/hb-loc-modal.js
Labels: Five Jars, PR: Code Reviewed, PR: Needs Work

#1926 [OYS-79] Add fix to use cellpading values in ckeditor tables of Rose …
  modules/custom/openy_ckeditor/js/openy_ckeditor.js
  modules/custom/openy_ckeditor/openy_ckeditor.libraries.yml
Labels: PR: Needs Review, PR: Needs Testing

#1929 [OYS-83] Fix openy_hours_formatter lib error in IE11
  modules/custom/openy_hours_formatter/js/luxon/luxon.js
  modules/custom/openy_hours_formatter/js/luxon/luxon.js.map
  modules/custom/openy_hours_formatter/js/luxon/luxon.min.js
  modules/custom/openy_hours_formatter/js/luxon/luxon.min.js.map
  modules/custom/openy_hours_formatter/js/openy_hours_formatter.js
  modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
  modules/custom/openy_hours_formatter/openy_hours_formatter.libraries.yml
  modules/custom/openy_system/openy_system.libraries.yml
Labels: Five Jars, PR: Code Reviewed, PR: Tested, Type: Bug

#1919 [OYS-76]: [Search] Link to main repository
  modules/custom/openy_search/openy_google_search/openy_google_search.module
Labels: PR: Needs Review, Type: Docs

#1921 [OYS-75]: [Search] Open Y Google Search installation
  modules/custom/openy_search/openy_google_search/openy_google_search.install
Labels: PR: Needs Review

#1925 [OYS-80]: Make BRANCH AMENITIES fieldset collapsible
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
Labels: PR: Needs Review, PR: Needs Testing

#1885 Os 625 fixed accessibility issues at schedules page
  modules/custom/openy_repeat/js/repeat.js
  modules/custom/openy_repeat/js/repeat/src/repeat.js
  modules/custom/openy_repeat/src/Controller/RepeatController.php
  modules/custom/openy_system/assets/js/atc.dev.js
  modules/custom/openy_system/assets/js/atc.js
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.libraries.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/src/scss/component/_addtocalendar.scss
  themes/openy_themes/openy_carnation/templates/openy_repeat/openy-repeat-schedule-dashboard--table.html.twig
  themes/openy_themes/openy_lily/css/print.css.map
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/css/style.css.map
  themes/openy_themes/openy_lily/sass/modules/_schedules.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_schedules.scss
Labels: PR: Code Reviewed, PR: Needs Work, PR: Tested

#1907 Externalize Vue libraries.
  composer.json
  composer.lock
  modules/custom/openy_activity_finder/openy_activity_finder.libraries.yml
  modules/custom/openy_activity_finder/openy_af_vue_app/dist/main.js
  modules/custom/openy_activity_finder/openy_af_vue_app/webpack.build.js
  modules/custom/openy_activity_finder/openy_af_vue_app/webpack.common.js
  modules/custom/openy_activity_finder/openy_af_vue_app/webpack.dev.js
  modules/custom/openy_repeat/openy_repeat.libraries.yml
  modules/custom/openy_system/openy_system.libraries.yml
Labels: PR: Needs Review, PR: Needs Testing
