Repository ymcatwincities/openy, pull requests merged in 2020-03, with the labels that each got.

#1934 Update JS polyfill to version 3.
  modules/custom/openy_system/openy_system.libraries.yml
Labels: Five Jars, Level: Advanced, PR: Code Reviewed, Type: Task

#1935 Empty space at Programs page + styling of location filters on mobile
  modules/custom/openy_map/templates/openy-map.html.twig
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_menu.scss
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_branch.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_location.scss
Labels: PR: Needs Review

#1937 Fix of weeks parameter calculation
  modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
Labels: PR: Needs Review

#1941 OS-738 style fixes
  modules/openy_features/openy_block/modules/openy_block_branch_contacts_info/templates/block-branch-contacts-info.html.twig
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_branch.scss
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/misc/_camps-locations.scss
  themes/openy_themes/openy_lily/sass/modules/_branch.scss
  themes/openy_themes/openy_lily/templates/block/block-branch-contacts-info.html.twig
  themes/openy_themes/openy_rose/templates/block/block-branch-contacts-info.html.twig
Labels: Level: Middle, PR: Code Reviewed

#1953 Deleted unused crop patch + updated libraries, required for Memberships.
  composer.json
  composer.lock
Labels: PR: Needs Review

#1949 Update the code to make it compatible with PHP 7.3
  modules/custom/activenet/src/ActivenetClient.php
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
Labels: PR: Needs Review

#1952 Fixing Link Field on Grid Column Template
  themes/openy_themes/openy_lily/templates/paragraphs/paragraph--grid-columns.html.twig
Labels: Level: Novice, PR: Code Reviewed, PR: Needs Testing, Severity: Normal, Type: Bug

#1963 [INOYI-8]: Demo Content Not Rendering Correctly
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_grid_col.scss
Labels: Five Jars, PR: Needs Review, PR: Needs Testing, Type: Bug

#1965 [INOYI-13] Location Finder: map marker popups have gray border.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
Labels: Five Jars, PR: Needs Review, PR: Needs Testing, Type: Bug

#1966 [INOYI-12] Small banner overlaps alerts.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_banner.scss
Labels: Five Jars, Level: Novice, PR: Code Reviewed, PR: Tested, Type: Bug

#1968 [YGO-16] fix breadcrumbs overlapping alert arrows.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_site-alert.scss
Labels: Five Jars, Level: Novice, PR: Code Reviewed, Severity: Minor, Type: Bug

#1969 [INOYI-15] Next/Prev buttons layout fixes in Membership calculator.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_membership.scss
  themes/openy_themes/openy_carnation/templates/form/input.html.twig
Labels: Five Jars, Level: Novice, PR: Code Reviewed, Severity: Normal, Type: Bug

#1961 [INOYI-10] hide map marker for empty branch in event
  themes/openy_themes/openy_carnation/templates/node/event/node--event--teaser.html.twig
Labels: Five Jars, PR: Needs Review, PR: Needs Testing, Type: Bug

#1978 Typo fix in openy_media_image module dependencies
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.info.yml
Labels: Five Jars, PR: Code Reviewed
