Repository ymcatwincities/openy, pull requests merged in 2020-09, with the labels that each got.

#2127 [YGO-170] Add Coming soon label to locations.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_locations.scss
  themes/openy_themes/openy_carnation/src/scss/presentation/_variables.scss
  themes/openy_themes/openy_carnation/templates/node/node--location-type--teaser.html.twig
Labels: PR: Code Reviewed, PR: Tested, Type: Enhancement

#2126 [CR-41] Fix for featured highlights and Featured Content paragraphs (carnation)
  modules/openy_features/openy_block/modules/openy_block_featured_highlights/config/install/core.entity_view_display.block_content.featured_highlights_block.default.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/openy_prgf_featured_highlights.install
  modules/openy_features/openy_prgf/modules/openy_prgf_featured_highlights/templates/paragraph--featured-highlights--default.html.twig
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/_utils.scss
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--featured-content--default.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--featured-highlights--default.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2134 [CR-42] Limit banner images by image style (carnation)
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/config/install/image.style.carnation_banner_1920_700.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.install
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--banner.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--small-banner.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2133 Carnation W3C fixes
  composer.json
  themes/openy_themes/openy_carnation/templates/block/block--system-menu-block--footer-menu-right.html.twig
  themes/openy_themes/openy_carnation/templates/elements/breadcrumb.html.twig
  themes/openy_themes/openy_carnation/templates/elements/pager.html.twig
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--grid-columns.html.twig
  themes/openy_themes/openy_carnation/templates/views/views-mini-pager.html.twig
  themes/openy_themes/openy_lily/templates/block/block--mainnavigation.html.twig
Labels: PR: Needs Review, PR: Needs Testing

#2137 [CR-42] Fix dependency to gallery config (crop.type.crop_1920_700)
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.info.yml
Labels: PR: Needs Review, PR: Needs Testing

#2142 Change jquery.ui to contribs
  composer.json
  openy.info.yml
  openy.install
  openy.libraries.yml
  themes/openy_themes/openy_campaign_theme/openy_campaign_theme.info.yml
  themes/openy_themes/openy_campaign_theme/openy_campaign_theme.install
  themes/openy_themes/openy_campaign_theme/openy_campaign_theme.libraries.yml
  themes/openy_themes/openy_lily/openy_lily.info.yml
  themes/openy_themes/openy_lily/openy_lily.install
  themes/openy_themes/openy_lily/openy_lily.libraries.yml
  themes/openy_themes/openy_rose/openy_rose.info.yml
  themes/openy_themes/openy_rose/openy_rose.install
  themes/openy_themes/openy_rose/openy_rose.libraries.yml
Labels: PR: DO NOT MERGE, Status: Under development

#2143 [CR-43] Fix blazy aspect ratio styles
  modules/openy_features/openy_media/css/blazy.ratio.css
  modules/openy_features/openy_media/openy_media.libraries.yml
  modules/openy_features/openy_media/openy_media.module
Labels: Five Jars, PR: Needs Testing, Status: Needs review, Type: Bug

#2154 Global constants in datetime.module are deprecated and DateTimeItemIn…
  modules/custom/openy_campaign/src/CampaignMenuService.php
  modules/custom/openy_campaign/src/Entity/MemberCheckin.php
  modules/custom/openy_campaign/src/Plugin/Block/CampaignRegisterBlock.php
  modules/custom/openy_myy/modules/ymca_personify/src/PersonifyApi.php
  modules/openy_features/openy_block/modules/openy_block_date/src/EntityOperations.php
Labels: Severity: Critical, Type: Bug

#2107 Upgrade webforms #2079
  composer.json
Labels: Level: Novice, PR: Code Reviewed, PR: Tested, Type: Experimental feature, dependencies

#2155 [RGTC-1281] Fix deprecated parameter for Openy Upgrade Tool
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogForm.php
Labels: Level: Middle, Severity: Critical, Type: Bug

#2173 Issue #2080
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Task, dependencies

#2179 Jquery ui 8x - replace deprecated with contribs
  composer.json
  openy.info.yml
  openy.install
  openy.libraries.yml
  themes/openy_themes/openy_campaign_theme/openy_campaign_theme.info.yml
  themes/openy_themes/openy_campaign_theme/openy_campaign_theme.install
  themes/openy_themes/openy_campaign_theme/openy_campaign_theme.libraries.yml
  themes/openy_themes/openy_lily/openy_lily.info.yml
  themes/openy_themes/openy_lily/openy_lily.install
  themes/openy_themes/openy_lily/openy_lily.libraries.yml
  themes/openy_themes/openy_rose/openy_rose.info.yml
  themes/openy_themes/openy_rose/openy_rose.install
  themes/openy_themes/openy_rose/openy_rose.libraries.yml
Labels: Level: Middle, PR: Code Reviewed, Severity: Normal, Type: Task, dependencies, javascript

#2185 [CR-21] Update simple_menu_icons to 8.x-2.x
  composer.json
Labels: PR: Code Reviewed, PR: Needs Testing, Type: Experimental feature

#2188 [CR-26] upgrade colorpicker.
  composer.json
  modules/openy_features/openy_demo_content/modules/openy_demo_tcolor/config/install/migrate_plus.migration.openy_demo_taxonomy_term_color.yml
  modules/openy_features/openy_node/openy_node.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_banner/openy_prgf_banner.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_small_banner/openy_prgf_small_banner.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/config/install/core.entity_form_display.taxonomy_term.color.default.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/config/install/core.entity_view_display.taxonomy_term.color.color.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/config/install/core.entity_view_display.taxonomy_term.color.default.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/config/install/field.field.taxonomy_term.color.field_color.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/config/install/field.storage.taxonomy_term.field_color.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/openy_txnm_color.info.yml
  modules/openy_features/openy_taxonomy/modules/openy_txnm_color/openy_txnm_color.install
  modules/openy_features/openy_taxonomy/openy_taxonomy.install
  patches/colorapi/enable_colorapi_field.patch
  patches/jquery_colorpicker/library_path_update.patch
  src/Form/ConfigureProfileForm.php
Labels: Five Jars, PR: Code Reviewed, PR: Needs Work, PR: Tested, Type: Task

#2189 [CR-18] Remove dependencies to media_entity_video, switch to core video media
  composer.json
  modules/openy_features/openy_media/modules/openy_media_local_video/config/install/media.type.video_local.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/openy_media_local_video.info.yml
  modules/openy_features/openy_media/modules/openy_media_video/openy_media_video.info.yml
  openy.install
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, Type: Task, dependencies

#2177 [CR-22] Update search_api_solr
  composer.json
  modules/custom/openy_activity_finder/config/optional/search_api.index.default.yml
  modules/custom/openy_activity_finder/config/optional/search_api.server.solr.yml
  modules/custom/openy_activity_finder/openy_activity_finder.install
  modules/custom/openy_activity_finder/src/OpenyActivityFinderSolrBackend.php
  modules/custom/openy_search/openy_search_api/config/install/search_api.server.solr_search.yml
  modules/custom/openy_search/openy_search_api/openy_search_api.install
  openy.profile
  src/Form/SearchSolrForm.php
Labels: Five Jars, Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Critical

#2206 Fix menu item error 500
  modules/openy_features/openy_demo_content/modules/openy_demo_menu/modules/openy_demo_menu_main/src/Plugin/migrate/process/OpenYMenuIcon.php
Labels: Level: Advanced, PR: Code Reviewed, Severity: Critical, Type: Bug

#2205 Remove custom formatters in favor of simple formatter
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/core.entity_view_display.block_content.branch_amenities.default.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/custom_formatters.formatter.branch_amenities.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/openy_block_branch_amenities.info.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/openy_block_branch_amenities.install
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/src/Plugin/Field/FieldFormatter/BranchAmenitiesFormatter.php
  modules/openy_features/openy_block/modules/openy_block_branch_contacts_info/openy_block_branch_contacts_info.info.yml
Labels: Level: Advanced, Severity: Important, Type: Bug

#2210 Fix locations filter
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.module
  modules/openy_features/openy_location/modules/openy_loc_filter/src/Form/LocationFilterSettingsForm.php
Labels: Level: Middle, Severity: Important, Type: Bug

#2212 Fix locations filter (#2210)
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.module
  modules/openy_features/openy_location/modules/openy_loc_filter/src/Form/LocationFilterSettingsForm.php
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Bug
