Repository ymcatwincities/openy, pull requests merged in 2020-05, with the labels that each got.

#2010 Updated views_data_export & webform
  composer.json
Labels: IXM, PR: Needs Review

#1997 [INOYI-27] Config update after enable media folders
  modules/openy_features/openy_media/config/install/taxonomy.vocabulary.media_tags.yml
  modules/openy_features/openy_media/modules/openy_media_document/config/install/core.entity_form_display.media.document.default.yml
  modules/openy_features/openy_media/modules/openy_media_document/config/install/core.entity_view_display.media.document.default.yml
  modules/openy_features/openy_media/modules/openy_media_document/config/install/media.type.document.yml
  modules/openy_features/openy_media/modules/openy_media_document/config/install/views.view.documents_library.yml
  modules/openy_features/openy_media/modules/openy_media_document/openy_media_document.info.yml
  modules/openy_features/openy_media/modules/openy_media_document/openy_media_document.install
  modules/openy_features/openy_media/modules/openy_media_image/config/install/core.entity_form_display.media.image.default.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/media.type.image.yml
  modules/openy_features/openy_media/modules/openy_media_image/config/install/views.view.images_library.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
  modules/openy_features/openy_media/modules/openy_media_local_video/config/install/core.entity_form_display.media.video_local.default.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/config/install/media.type.video_local.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/config/install/views.view.local_videos_library.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/openy_media_local_video.info.yml
  modules/openy_features/openy_media/modules/openy_media_local_video/openy_media_local_video.install
  modules/openy_features/openy_media/modules/openy_media_video/config/install/core.entity_form_display.media.video.default.yml
  modules/openy_features/openy_media/modules/openy_media_video/config/install/core.entity_view_display.media.video.default.yml
  modules/openy_features/openy_media/modules/openy_media_video/config/install/views.view.videos_library.yml
  modules/openy_features/openy_media/modules/openy_media_video/openy_media_video.info.yml
  modules/openy_features/openy_media/modules/openy_media_video/openy_media_video.install
  modules/openy_features/openy_media/openy_media.info.yml
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#2013 [YGO-99] replace blazy image styles in CKeditor.
  modules/openy_features/openy_media/modules/openy_media_image/config/install/embed.button.embed_image.yml
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Bug

#2014 [YGO-99] Fix for full_without_blazy plugin does not exist
  modules/openy_features/openy_media/modules/openy_media_image/config/install/embed.button.embed_image.yml
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, Severity: Critical, Type: Bug

#1991 [OYS-81] Backport YLI Location Filter settings form
  modules/custom/openy_data_wrapper/src/DataWrapper.php
  modules/openy_features/openy_location/modules/openy_loc_filter/config/install/openy_loc_filter.location_filter_settings.yml
  modules/openy_features/openy_location/modules/openy_loc_filter/js/location_filter.js
  modules/openy_features/openy_location/modules/openy_loc_filter/js/location_filter/README.MD
  modules/openy_features/openy_location/modules/openy_loc_filter/js/location_filter/babel.config.js
  modules/openy_features/openy_location/modules/openy_loc_filter/js/location_filter/package.json
  modules/openy_features/openy_location/modules/openy_loc_filter/js/location_filter/src/location_filter.js
  modules/openy_features/openy_location/modules/openy_loc_filter/js/location_filter/webpack.config.js
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.info.yml
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.install
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.libraries.yml
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.links.menu.yml
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.module
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.routing.yml
  modules/openy_features/openy_location/modules/openy_loc_filter/src/Form/LocationFilterSettingsForm.php
  openy.packages.yml
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, Type: Feature

#2012 preparation for Membership Framework
  composer.json
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/field.storage.node.field_lp_layout.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.install
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.module
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/templates/field/field--block-content--field-sb-body--simple-block.html.twig
  themes/openy_themes/openy_carnation/templates/field/field--link.html.twig
  themes/openy_themes/openy_carnation/templates/field/field--paragraph--1c.html.twig
  themes/openy_themes/openy_carnation/templates/field/field.html.twig
  themes/openy_themes/openy_carnation/templates/node/include/header-default.html.twig
  themes/openy_themes/openy_carnation/templates/node/node--landing-page--full.html.twig
  themes/openy_themes/openy_lily/templates/node/include/node--landing-page--two-columns-left.html.twig
  themes/openy_themes/openy_lily/templates/node/node--landing-page--full.html.twig
  themes/openy_themes/openy_rose/templates/node/node--landing-page--full.html.twig
Labels: IXM, Level: Advanced, PR: Code Reviewed, PR: DO NOT MERGE, PR: Needs clarification, Type: Docs, Type: Feature

#2015 Branch Amenities: Closed Amenities
  modules/custom/openy_ckeditor/openy_ckeditor.module
  modules/custom/openy_ckeditor/templates/list-branch-amenities.html.twig
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/core.entity_form_display.paragraph.branch_amenities.default.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/core.entity_view_display.paragraph.branch_amenities.default.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/field.field.paragraph.branch_amenities.field_amenities_block.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/field.storage.paragraph.field_amenities_block.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/config/install/paragraphs.paragraphs_type.branch_amenities.yml
  modules/openy_features/openy_block/modules/openy_block_branch_amenities/openy_block_branch_amenities.install
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_form_display.node.branch.default.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.default.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_amenities_closed.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/field.storage.node.field_location_amenities_closed.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_amenities.scss
  themes/openy_themes/openy_carnation/templates/field/field--paragraph--field-amenities-block--branch-amenities.html.twig
Labels: IXM, PR: Code Reviewed, PR: Needs Testing, Type: Enhancement

#1950 [INOYI-1]: Remove deprecated entity.query service from Drupal\openy_r…
  modules/custom/openy_repeat/src/RepeatManager.php
  modules/custom/openy_session_instance/openy_session_instance.services.yml
  modules/custom/openy_session_instance/src/SessionInstanceManager.php
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#2008 Alerts Enhancements
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.services.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/src/BranchAlertBuilder.php
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.services.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/src/CampAlertBuilder.php
  modules/openy_features/openy_location/modules/openy_loc_facility/openy_loc_facility.services.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/src/FacilityAlertBuilder.php
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_form_display.node.alert.default.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.default.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.node_alert_footer.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.node_alert_header.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/core.entity_view_display.node.alert.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/field.field.node.alert.field_alert_location.yml
  modules/openy_features/openy_node/modules/openy_node_alert/config/install/field.storage.node.field_alert_location.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.info.yml
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.services.yml
  modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php
  modules/openy_features/openy_node/modules/openy_node_alert/src/Service/AlertBuilderInterface.php
  modules/openy_features/openy_node/modules/openy_node_alert/src/Service/AlertManager.php
  modules/openy_features/openy_node/modules/openy_node_blog/openy_node_blog.services.yml
  modules/openy_features/openy_node/modules/openy_node_blog/src/BlogAlertBuilder.php
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/core.entity_form_display.node.landing_page.default.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/core.entity_view_display.node.landing_page.default.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/core.entity_view_display.node.landing_page.full.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/core.entity_view_display.node.landing_page.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/field.field.node.landing_page.field_bottom_content.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/field.field.node.landing_page.field_lp_location.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/field.field.node.landing_page.field_meta_tags.yml
  modules/openy_features/openy_node/modules/openy_node_landing/config/install/field.storage.node.field_lp_location.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.info.yml
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.install
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.services.yml
  modules/openy_features/openy_node/modules/openy_node_landing/src/LandingPageAlertBuilder.php
  modules/openy_features/openy_node/modules/openy_node_news/openy_node_news.services.yml
  modules/openy_features/openy_node/modules/openy_node_news/src/NewsAlertBuilder.php
  openy.install
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, Type: Enhancement
