Repository ymcatwincities/openy, pull requests merged in 2020-07, with the labels that each got.

#2046 Make gallery heading optional
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/config/install/field.field.paragraph.gallery.field_prgf_headline.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.install
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--gallery--default.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--gallery-cta-content.html.twig
  themes/openy_themes/openy_lily/templates/paragraphs/paragraph--gallery--default.html.twig
  themes/openy_themes/openy_lily/templates/paragraphs/paragraph--gallery-cta-content.html.twig
  themes/openy_themes/openy_rose/templates/paragraph/paragraph--gallery--default.html.twig
Labels: PR: Code Reviewed, PR: Needs Testing, Type: Bug, Type: Enhancement

#2054 [VYMCA-63] Virtual Y: Close mobile menu on the menu link click
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_lily/scripts/openy_lily.js
  themes/openy_themes/openy_rose/scripts/openy_rose.js
Labels: Five Jars, PR: Needs Review, PR: Needs Testing

#2056 [YPKCOY-37] Fix Notice: Undefined index
  modules/openy_features/openy_node/modules/openy_node_landing/openy_node_landing.module
  modules/openy_features/openy_node/src/BatchNodeUpdate.php
Labels: Five Jars, PR: Needs Review, Type: Bug

#2059 [YPKCOY-82] Fix sticky sidebar when alert height is undefined (Carnation)
  themes/openy_themes/openy_carnation/dist/js/openy_carnation_landing.js
  themes/openy_themes/openy_carnation/dist/js/openy_carnation_sticky_sidebar.js
Labels: Five Jars, Status: Needs review, Type: Bug
