Repository ymcatwincities/openy, pull requests merged in 2020-08, with the labels that each got.

#2066 [CR-2] Update language on Open Y Terms & Conditions
  src/Form/TermsOfUseForm.php
Labels: Five Jars, PR: Needs Review

#2084 Patches cleanup
  composer.json
  patches/geysir/add-reload-page.patch
Labels: IXM, PR: Needs Review

#2085 [Carnation]: Fix embedded images and videos alignment
  modules/custom/openy_ckeditor/css/openy_ckeditor.admin.css
  modules/custom/openy_ckeditor/openy_ckeditor.module
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/src/scss/_base.scss
  themes/openy_themes/openy_carnation/src/scss/component/_embedded_content.scss
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2086 Fix the fatal error on Locations page
  modules/custom/openy_data_wrapper/src/DataWrapper.php
Labels: Five Jars, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug

#2088 Fix squashed Open Y Rose embedded images
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_landing.scss
Labels: Five Jars, PR: Needs Review, PR: Needs Testing

#2087 Carnation: Gallery fixes and improvements
  composer.json
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/config/install/image.style.gallery_thumbnail.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/js/openy_prgf_gallery.carnation.js
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.install
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.libraries.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_gallery.scss
  themes/openy_themes/openy_carnation/src/scss/presentation/_variables.scss
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--gallery--default.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2092 [CR-25] Fix alias_manager dependency to unblock Open Y Extended/Custom
  modules/custom/openy_activity_finder/src/Plugin/Block/ActivityFinderBlock.php
  modules/custom/openy_activity_finder/src/Plugin/Block/CampFinderBlock.php
  modules/custom/openy_search/openy_google_search/openy_google_search.services.yml
  modules/custom/openy_search/openy_google_search/src/OpenyGoogleSearchHelperService.php
  modules/custom/openy_search/openy_search_api/openy_search_api.module
  modules/openy_features/openy_node/modules/openy_node_alert/openy_node_alert.install
  openy.info.yml
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#2102 [YPKCOY-134] Let link attributes work
  themes/openy_themes/openy_carnation/templates/field/field--link.html.twig
  themes/openy_themes/openy_carnation/templates/field/field--paragraph--field-prgf-link--gallery.html.twig
Labels: Five Jars, PR: Needs Review, PR: Needs Testing

#2103 [CR-27] Home branch sorting fix (Carnation refactoring)
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/js/hb-location-finder-override.js
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
  themes/openy_themes/openy_carnation/templates/views/views-view-unformatted--locations.html.twig
Labels: Five Jars, PR: Needs Review, PR: Tested

#2106 Upgrade migrate subsystem
  composer.json
Labels: Level: Advanced, PR: Code Reviewed, PR: Needs Testing, Severity: Important, Type: Experimental feature

#2105 Update paragraphs to latest stable version #2077
  composer.json
Labels: PR: Code Reviewed, PR: Tested, Severity: Important, Type: Task, dependencies

#2108 [CR-31] Fix event page full template and calendar
  modules/openy_features/openy_node/modules/openy_node_event/js/openy_node_event.js
  themes/openy_themes/openy_carnation/templates/node/event/node--event--full.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2109 Fix twig replace style #2096
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
  themes/openy_themes/openy_carnation/templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig
Labels: Level: Novice, Severity: Critical, Type: Bug

#2110 Fix twig replace style #2096 (#2109)
  modules/custom/openy_repeat/templates/openy-repeat-schedule-dashboard--sidebar.html.twig
  themes/openy_themes/openy_carnation/templates/openy_repeat/openy-repeat-schedule-dashboard--sidebar.html.twig
Labels: PR: Code Reviewed, Severity: Important, Type: Bug

#2113 Issue 2100 - error 500
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php
  modules/custom/openy_group_schedules/openy_group_schedules.module
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
  modules/custom/openy_group_schedules/src/Form/GroupexFormLocation.php
  modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php
  modules/custom/openy_redirect/openy_redirect.module
  modules/custom/openy_upgrade_tool/src/Controller/OpenyUpgradeLogController.php
  modules/openy_features/openy_taxonomy/src/Plugin/views/filter/BetterTaxonomyIndexTid.php
Labels: Level: Advanced, PR: Code Reviewed, PR: Needs Testing, Severity: Critical, Type: Bug

#2115 Backport EntityManager change from 9.x-2.x issue #2100
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php
  modules/custom/openy_group_schedules/openy_group_schedules.module
  modules/custom/openy_group_schedules/src/Form/GroupexFormFull.php
  modules/custom/openy_group_schedules/src/Form/GroupexFormLocation.php
  modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php
  modules/custom/openy_redirect/openy_redirect.module
  modules/custom/openy_upgrade_tool/src/Controller/OpenyUpgradeLogController.php
  modules/openy_features/openy_taxonomy/src/Plugin/views/filter/BetterTaxonomyIndexTid.php
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Enhancement

#2117 Carnation fixes
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.install
  modules/openy_features/openy_block/modules/openy_block_menu/openy_block_menu.module
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/core.entity_view_display.node.branch.teaser.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
  modules/openy_features/openy_location/modules/openy_loc_camp/config/install/core.entity_view_display.node.camp.teaser.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/config/install/core.entity_view_display.node.facility.teaser.yml
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/src/scss/modules/_gtranslate.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_header.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_location.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_locations.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_menu.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_microsites.scss
  themes/openy_themes/openy_carnation/templates/field/field--field-location-directions--teaser.html.twig
  themes/openy_themes/openy_carnation/templates/node/camp/node--camp--teaser.html.twig
  themes/openy_themes/openy_carnation/templates/node/node--location-type--teaser.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2122 [RGTC-1280] Replace deprecated method rightJoin
  modules/custom/openy_repeat/src/Controller/RepeatController.php
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Type: Bug

#2121 Issue 2097
  modules/custom/openy_hours_formatter/src/HoursToday.php
  modules/custom/openy_popups/src/PopupLinkGenerator.php
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug

#2123 [CR-32] Fix grid content col on ipad
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_grid_col.scss
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--grid-content--default.html.twig
Labels: Five Jars, PR: Needs Review, PR: Needs Testing

#2125 [CR-40] Four columns paragraph fix (carnation)
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_columns.scss
  themes/openy_themes/openy_carnation/templates/field/field--paragraph--4c.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--4c.html.twig
Labels: Five Jars, PR: Needs Review, PR: Needs Testing
