Repository ymcatwincities/openy, pull requests merged in 2020-04, with the labels that each got.

#1986 [YGO-27] Fix events listing paragraph teaser in Carnation
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.module
  themes/openy_themes/openy_carnation/templates/node/event/node--event--teaser.html.twig
  themes/openy_themes/openy_lily/templates/node/node--event--teaser.html.twig
  themes/openy_themes/openy_rose/templates/node/node--event--teaser.html.twig
Labels: Five Jars, Level: Middle, PR: Code Reviewed, Severity: Normal, Type: Bug

#1985 [YGO-24] Carnation theme fixes for event page
  modules/openy_features/openy_node/modules/openy_node_event/openy_node_event.module
  modules/openy_features/openy_node/modules/openy_node_event/templates/event-date-info.html.twig
  themes/openy_themes/openy_carnation/templates/node/event/event-contact-info.html.twig
  themes/openy_themes/openy_carnation/templates/node/event/event-date-info.html.twig
Labels: Five Jars, Level: Middle, PR: Code Reviewed, PR: Needs Testing, Type: Bug

#1984 [INOYI-16] Microsites menu issues.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_gallery.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_microsites.scss
  themes/openy_themes/openy_carnation/src/scss/modules/_site-alert.scss
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_banner.scss
  themes/openy_themes/openy_carnation/templates/field/field--field-menu-block-links.html.twig
  themes/openy_themes/openy_carnation/templates/page/page.html.twig
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--microsites-menu.html.twig
Labels: Five Jars, Level: Middle, Severity: Normal, Status: Under discussion, Type: Enhancement

#1970 [INOYI-17] Don't render empty sidebar if empty.
  themes/openy_themes/openy_carnation/templates/node/event/node--event--full.html.twig
Labels: Five Jars, Level: Middle, PR: Code Reviewed, PR: Needs Testing, Severity: Normal, Type: Bug, Type: Enhancement

#1976 [INOYI-22]: [Rose theme] Half size image alignment
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/base/_utilities.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/base/_utilities.scss
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#1973 [INOYI-5]: Program registration paragraph does not work in Sandbox
  modules/custom/openy_programs_search/src/Plugin/Block/ProgramsSearchBlock.php
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#1972 [INOYI-4]: Hide Drupal themes from the list of available themes on th…
  modules/custom/openy_system/openy_system.install
  modules/custom/openy_system/openy_system.module
  modules/custom/openy_system/openy_system.permissions.yml
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#1977 [INOYI-18] Remove overlay from Gallery if displayed not in the header
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_gallery.scss
  themes/openy_themes/openy_carnation/templates/node/include/header-default.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, PR: Needs Work

#1990 Delete composer.lock
  composer.lock
Labels: Level: Middle, Type: Task, dependencies

#1960 [INOYI-6]: Fix carnation's buggy modal closing behaviour
  themes/openy_themes/openy_carnation/dist/js/openy_carnation.js
  themes/openy_themes/openy_carnation/dist/main.js
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#1983 Upgrade captcha
  composer.json
Labels: PR: DO NOT MERGE

#1993 [INOYI-19]: Closing quotation mark does not appear for Story Card
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_paragraphs.scss
  themes/openy_themes/openy_lily/templates/paragraphs/paragraph--story-card--default.html.twig
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_paragraphs.scss
  themes/openy_themes/openy_rose/templates/paragraph/paragraph--story-card--default.html.twig
Labels: Five Jars, Level: Middle, PR: Code Reviewed, Type: Bug

#1998 In Teaser paragraph, do not display link field if empty.
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--teaser--default.html.twig
Labels: Level: Middle, PR: Code Reviewed, Type: Bug

#2000 Fix syntax error in Program Search block
  modules/custom/openy_programs_search/src/Plugin/Block/ProgramsSearchBlock.php
Labels: Five Jars, Level: Novice, PR: Code Reviewed, Type: Bug

#1999 Activity Finder: fix possible negative values come from Daxko when no…
  modules/custom/openy_activity_finder/templates/openy-activity-finder-program-search-page.html.twig
Labels: IXM, Level: Advanced, PR: Code Reviewed, Type: Bug

#1996 To make OpenY Focal Point work with Grid Columns
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointImageWidget.php
Labels: IXM, Level: Advanced, PR: Code Reviewed, Type: Bug, Type: Enhancement

#2002 [INOYI-28] Update contrib modules part 1
  composer.json
  modules/custom/openy_calc/openy_calc.module
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/core.entity_form_display.node.social_post.default.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/views.view.social_posts.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/config/install/views.view.social_posts_view.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.info.yml
  modules/openy_features/openy_node/modules/openy_node_social_post/openy_node_social_post.install
  themes/openy_themes/openy_rose/openy_rose.theme
Labels: Five Jars, Level: Middle, PR: Code Reviewed, PR: Tested, dependencies

#2003 [YGO-97] Fix system modal height on schedules.
  modules/custom/openy_repeat/css/repeat.css
Labels: PR: Needs Review, PR: Needs Testing

#1932 [OYS-74]: Add notification about changes in Image entity browser configs
  modules/openy_features/openy_media/modules/openy_media_image/openy_media_image.install
Labels: Five Jars, PR: Code Reviewed, PR: Needs Work, PR: Tested, Type: Enhancement
