Repository ymcatwincities/openy, pull requests merged in 2021-09, with the labels that each got.

#2544 [MAINTAIN-155] fixed issue with not working modal dialog on membership (/join) page on Carnation theme
  modules/custom/openy_calc/js/openy_calc.js
Labels: PR: Code Reviewed, PR: Needs Testing, Five Jars

#2547 fix(join-form): prevent Google Translate from affecting submit buttons #2546
  modules/custom/openy_calc/src/Form/CalcBlockForm.php
Labels: PR: Code Reviewed, PR: Tested, Level: Middle, Type: Bug, Severity: Normal, javascript

#2549 feat(decoupe): Decouple activenet from Open Y repo to Drupal.org
  composer.json
  modules/custom/activenet/README.md
  modules/custom/activenet/activenet.info.yml
  modules/custom/activenet/activenet.links.menu.yml
  modules/custom/activenet/activenet.module
  modules/custom/activenet/activenet.permissions.yml
  modules/custom/activenet/activenet.routing.yml
  modules/custom/activenet/activenet.services.yml
  modules/custom/activenet/config/install/activenet.settings.yml
  modules/custom/activenet/src/ActivenetClient.php
  modules/custom/activenet/src/ActivenetClientException.php
  modules/custom/activenet/src/ActivenetClientFactory.php
  modules/custom/activenet/src/ActivenetClientFactoryInterface.php
  modules/custom/activenet/src/ActivenetClientInterface.php
  modules/custom/activenet/src/Form/SettingsForm.php
Labels: Level: Advanced, dependencies, Backporting, Decoupling

#2550 feat(decouple): Decouple Personify to Drupal.org
  composer.json
  modules/custom/personify/README.md
  modules/custom/personify/config/install/personify.settings.yml
  modules/custom/personify/personify.info.yml
  modules/custom/personify/personify.module
  modules/custom/personify/personify.routing.yml
  modules/custom/personify/personify.services.yml
  modules/custom/personify/src/Form/PersonifySettingsForm.php
  modules/custom/personify/src/PersonifyClient.php
  modules/custom/personify/src/PersonifySSO.php
Labels: PR: Code Reviewed, Level: Advanced, dependencies, Backporting, Decoupling

#2545 [carnation] Fix for openy subcategory page image resize issue.
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/dist/main.js
  themes/openy_themes/openy_carnation/src/scss/modules/_program.scss
Labels: Level: Middle, Type: Bug, Severity: Normal, javascript

#2400 Add support for Google Analytics v4
  composer.json
Labels: PR: Code Reviewed, Level: Middle, Status: Under discussion, Type: Experimental feature, dependencies

#2554 fix(deps): Add openy_er from drupal.org
  composer.json
  modules/custom/openy_er/README.md
  modules/custom/openy_er/openy_er.info.yml
  modules/custom/openy_er/openy_er.module
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/BlockSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/DefaultSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/NodeSelectionNoDependency.php
  modules/custom/openy_er/src/Plugin/EntityReferenceSelection/SelectionNoDependencyTrait.php
Labels: Level: Advanced, Type: Task, dependencies, Backporting, Daxko, Decoupling

#2543 [MAINTAIN-166] fixed issue with images on the blog post page for mobile screen
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_blog.scss
Labels: PR: Code Reviewed, PR: Needs clarification, PR: Needs Testing, Five Jars

#2561 feat(decouple): Openy addthis from drupal.org
  composer.json
  modules/custom/openy_addthis/config/install/openy_addthis.settings.yml
  modules/custom/openy_addthis/config/install/paragraphs.paragraphs_type.addthis.yml
  modules/custom/openy_addthis/js/addthis.js
  modules/custom/openy_addthis/openy_addthis.info.yml
  modules/custom/openy_addthis/openy_addthis.install
  modules/custom/openy_addthis/openy_addthis.libraries.yml
  modules/custom/openy_addthis/openy_addthis.links.menu.yml
  modules/custom/openy_addthis/openy_addthis.module
  modules/custom/openy_addthis/openy_addthis.routing.yml
  modules/custom/openy_addthis/openy_addthis.services.yml
  modules/custom/openy_addthis/src/Entity/AddThisUninstallValidator.php
  modules/custom/openy_addthis/src/Form/OpenyAddThisSettingsForm.php
  modules/custom/openy_addthis/src/Form/PrepareUninstallForm.php
Labels: Level: Middle, Type: Task, dependencies, Backporting, Decoupling

#2562 feat(decouple): Openy gtranslate from drupal.org
  composer.json
  modules/custom/openy_gtranslate/js/openy_gtranslate.js
  modules/custom/openy_gtranslate/openy_gtranslate.info.yml
  modules/custom/openy_gtranslate/openy_gtranslate.install
  modules/custom/openy_gtranslate/openy_gtranslate.libraries.yml
  modules/custom/openy_gtranslate/openy_gtranslate.module
  modules/custom/openy_gtranslate/src/Plugin/Block/OpenYGTranslateBlock.php
  modules/custom/openy_gtranslate/templates/openy-gtranslate.html.twig
Labels: PR: Code Reviewed, Level: Middle, Type: Task, Severity: Normal, dependencies, javascript, Decoupling
