Repository ymcatwincities/openy, pull requests merged in 2021-07, with the labels that each got.

#2505 [MAINTAIN-116] Fix blog listings on Carnation
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/templates/views/views-view-unformatted--taxonomy-term--blog.html.twig
Labels: Five Jars, PR: Needs Review, PR: Needs Testing

#2507 [MAINTAIN-102] Decouple essential demo content
  composer.json
  openy.profile
Labels: Five Jars, Level: Advanced, PR: Code Reviewed, PR: Tested, dependencies

#2514 Unlimited programs should be opened for users
  modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
Labels: Daxko, PR: Needs Review, PR: Needs Testing

#2519 Update Leaflet library to the latest version v1.7.1
  modules/custom/openy_map/openy_map.libraries.yml
Labels: PR: Code Reviewed, PR: Tested, javascript

#2486 feat(decouple): openy map
  composer.json
  modules/custom/openy_map/config/install/openy_map.settings.yml
  modules/custom/openy_map/config/install/views.view.locations.yml
  modules/custom/openy_map/css/jquery.multiselect.css
  modules/custom/openy_map/css/map.css
  modules/custom/openy_map/img/map_icon_blue.png
  modules/custom/openy_map/img/map_icon_green.png
  modules/custom/openy_map/img/map_icon_purple.png
  modules/custom/openy_map/img/other/map_icon_red.png
  modules/custom/openy_map/img/other/map_icon_red_x2.png
  modules/custom/openy_map/js/jquery.multiselect.js
  modules/custom/openy_map/js/map.js
  modules/custom/openy_map/js/map/README.MD
  modules/custom/openy_map/js/map/babel.config.js
  modules/custom/openy_map/js/map/package.json
  modules/custom/openy_map/js/map/src/map.js
  modules/custom/openy_map/js/map/webpack.config.js
  modules/custom/openy_map/openy_map.info.yml
  modules/custom/openy_map/openy_map.install
  modules/custom/openy_map/openy_map.libraries.yml
  modules/custom/openy_map/openy_map.links.menu.yml
  modules/custom/openy_map/openy_map.module
  modules/custom/openy_map/openy_map.routing.yml
  modules/custom/openy_map/openy_map.services.yml
  modules/custom/openy_map/src/Element/OpenYMap.php
  modules/custom/openy_map/src/Form/SettingsForm.php
  modules/custom/openy_map/src/OpenyMapManager.php
  modules/custom/openy_map/src/Plugin/Block/LocationFinder.php
  modules/custom/openy_map/src/Plugin/Block/LocationFinderFilters.php
  modules/custom/openy_map/templates/openy-map.html.twig
Labels: Backporting, Decoupling, Level: Middle, PR: Code Reviewed, PR: Tested, Type: Task, dependencies

#2523 feat(deps): Link back decoupled openy_focal_point
  composer.json
  modules/custom/openy_focal_point/css/openy_focal_point.css
  modules/custom/openy_focal_point/js/openy_focal_point.js
  modules/custom/openy_focal_point/openy_focal_point.info.yml
  modules/custom/openy_focal_point/openy_focal_point.install
  modules/custom/openy_focal_point/openy_focal_point.libraries.yml
  modules/custom/openy_focal_point/openy_focal_point.module
  modules/custom/openy_focal_point/openy_focal_point.routing.yml
  modules/custom/openy_focal_point/src/Ajax/RerenderThumbnailCommand.php
  modules/custom/openy_focal_point/src/Controller/OpenYFocalPointPreviewController.php
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointCropForm.php
  modules/custom/openy_focal_point/src/Form/OpenYFocalPointEditForm.php
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointEntityReferenceBrowserWidget.php
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointImageWidget.php
  modules/custom/openy_focal_point/src/Plugin/ImageEffect/OpenYCropEffect.php
  modules/custom/openy_focal_point/src/Plugin/ImageEffect/OpenYFocalPointScaleAndCropImageEffect.php
  modules/custom/openy_focal_point/templates/openy-focal-point-preview.html.twig
Labels: Backporting, Decoupling, PR: Code Reviewed, PR: Tested
