Repository ymcatwincities/openy, pull requests merged in 2021-05, with the labels that each got.

#2447 Fix for Locations Filter
  modules/openy_features/openy_location/modules/openy_loc_filter/src/Form/LocationFilterSettingsForm.php
Labels: PR: Code Reviewed, Type: Bug

#2448 Resolved quick edit issue for main navigation.
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_menu.scss
Labels: PR: Needs Work

#2449 Bug Fix. Add jquery_ui_touch_punch
  composer.json
Labels: PR: Code Reviewed, PR: Tested, Type: Bug, dependencies

#2454 Cleanup old patches
  composer.json
Labels: PR: Code Reviewed, Severity: Normal, Type: Task, dependencies

#2461 Accessibility for embed YouTube
  composer.json
Labels: Level: Middle, PR: Code Reviewed, Type: Bug, dependencies

#2460 [MAINTAIN-8] added aria-hidden attribute to 'Add to calendar' link for GroupEx schedule table for all three themes
  themes/openy_themes/openy_carnation/templates/openy_group_schedules/groupex-table-class-individual.html.twig
  themes/openy_themes/openy_carnation/templates/openy_group_schedules/groupex-table-class.html.twig
  themes/openy_themes/openy_carnation/templates/openy_group_schedules/groupex-table-instructor-individual.html.twig
  themes/openy_themes/openy_lily/templates/openy_group_schedules/groupex-table-class-individual.html.twig
  themes/openy_themes/openy_lily/templates/openy_group_schedules/groupex-table-class.html.twig
  themes/openy_themes/openy_lily/templates/openy_group_schedules/groupex-table-instructor-individual.html.twig
  themes/openy_themes/openy_rose/templates/custom/groupex-table-class-individual.html.twig
  themes/openy_themes/openy_rose/templates/custom/groupex-table-class.html.twig
  themes/openy_themes/openy_rose/templates/custom/groupex-table-instructor-individual.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing
