Repository ymcatwincities/openy, pull requests merged in 2021-03, with the labels that each got.

#2411 [MAINTAIN-35] changed image style for paragraph teaser display view of media image
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/core.entity_view_display.media.image.prgf_teaser.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/crop.type.crop_520_440.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/config/install/image.style.paragraph_teaser_520_440.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_teaser/openy_prgf_teaser.install
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2417 [MAINTAIN-30] fixed layout for a taxonomy term pages
  themes/openy_themes/openy_carnation/openy_carnation.theme
  themes/openy_themes/openy_carnation/templates/page/page--taxonomy--term.html.twig
  themes/openy_themes/openy_carnation/templates/views/views-view-unformatted--taxonomy_term.html.twig
  themes/openy_themes/openy_carnation/templates/views/views-view.html.twig
Labels: PR: DO NOT MERGE

#2418 Update README.md
  modules/custom/openy_pef_gxp_sync/README.md
Labels: PR: Code Reviewed, Type: Docs

#2419 #2413 Carnation display Content paragraphs
  themes/openy_themes/openy_carnation/templates/node/blog/node--blog--full.html.twig
  themes/openy_themes/openy_carnation/templates/node/event/node--event--full.html.twig
  themes/openy_themes/openy_carnation/templates/node/news/node--news--full.html.twig
Labels: Backporting, Level: Novice, PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Bug, good first issue

#2420 [PRODDEV-240] Display search input field for the lily theme, backport…
  composer.json
  modules/custom/openy_search/openy_search_api/config/install/search_api.index.search_content.yml
  modules/custom/openy_search/openy_search_api/openy_search_api.install
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_global-search.scss
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2426 Fix upgrade path accidental module uninstallation issue
  modules/openy_features/openy_prgf/modules/openy_prgf_gallery/openy_prgf_gallery.info.yml
Labels: Type: Bug, dependencies
