Repository ymcatwincities/openy, pull requests merged in 2021-06, with the labels that each got.

#2458 [MAINTAIN-33] fixed icons for paragraph grid columns for Carnation theme
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/paragraphs/_grid_col.scss
  themes/openy_themes/openy_carnation/templates/paragraph/paragraph--grid-columns.html.twig
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#2441 Updated the event listing view page filter.
  modules/openy_features/openy_prgf/modules/openy_prgf_event_latest/config/install/views.view.latest_event_posts.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_event_latest/openy_prgf_event_latest.install
  modules/openy_features/openy_prgf/modules/openy_prgf_event_listing/config/install/views.view.listing_event_posts.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_event_listing/openy_prgf_event_listing.install
Labels: PR: Code Reviewed, PR: Needs Testing

#2459 Update contrib modules
  composer.json
Labels: PR: Code Reviewed, Type: Task

#2464 Remove block which is not used
  modules/custom/openy_group_schedules/src/GroupexScheduleFetcher.php
Labels: Daxko, Level: Middle, PR: Code Reviewed, Severity: Minor, Type: Task

#2465 [MAINTAIN-80] fixed not working the "Display the search form" option in theme settings
  modules/custom/openy_search/openy_google_search/openy_google_search.module
  modules/custom/openy_search/openy_search_api/openy_search_api.module
  openy.install
  themes/openy_themes/openy_lily/config/install/openy_lily.settings.yml
  themes/openy_themes/openy_rose/config/install/openy_rose.settings.yml
Labels: Level: Middle, Type: Bug

#2469 Add timeout for http request in openy_update module
  modules/custom/openy_update/openy_update.module
Labels: Type: Bug

#2468 [PRODDEV-246] added default values for location filter in the Membership Calc form
  modules/openy_features/openy_location/modules/openy_loc_filter/config/install/openy_loc_filter.location_filter_settings.yml
  modules/openy_features/openy_location/modules/openy_loc_filter/openy_loc_filter.module
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2467 Move Blazy ratio CSS fix to theme level
  modules/openy_features/openy_media/openy_media.libraries.yml
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2466 [MAINTAIN-5] fixed an error message for the 'Type' option in the Membership Calc form
  modules/custom/openy_calc/src/Form/CalcBlockForm.php
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2451 Remove media_entity_document
  composer.json
Labels: Level: Middle, PR: Code Reviewed, Severity: Important, Type: Task, dependencies

#2478 Remove hidden H1 tag from the google translate widget
  modules/custom/openy_gtranslate/js/openy_gtranslate.js
Labels: PR: Code Reviewed, PR: Needs Testing

#2480 Add the hook_openy_daxko2_activity_finder_daxko_params_alter()
  modules/custom/openy_daxko2/openy_daxko2.api.php
  modules/custom/openy_daxko2/openy_daxko2.services.yml
  modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
Labels: Daxko, Level: Advanced, Needs approval, PR: Code Reviewed, PR: Needs Testing, Type: Enhancement

#2450 Deprecating Activity Finder 3.x branch. We have it in 4.x branch for upgrade needs
  composer.json
Labels: Backporting, Level: Middle, PR: Code Reviewed, PR: Tested, Type: Task, dependencies

#2487 Activity Finder Daxko backend refactoring
  modules/custom/openy_daxko2/openy_daxko2.services.yml
  modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
Labels: Daxko, PR: Needs Review, PR: Needs Testing

#2484 feat(decouple): openy_node_alert
  composer.json
Labels: Decoupling, Level: Middle, PR: Code Reviewed, PR: Tested, Type: Task

#2476 Fix popper.js library missing
  themes/openy_themes/openy_carnation/openy_carnation.libraries.yml
Labels: Backporting, IXM, Level: Middle, PR: Needs Work, Type: Bug, javascript

#2489 feat(decouple): Check openy_demo_content
  composer.json
Labels: Backporting, Decoupling, Level: Middle, PR: Code Reviewed, PR: Tested, Type: Task

#2488 fix(cleanup)!: Remove jQuery Colorpicker
  composer.json
Labels: Level: Middle, PR: Tested, Severity: Normal, Type: Task, dependencies

#2485 feat(decouple): Backport OpenY Hours Formatter
  composer.json
  modules/custom/openy_hours_formatter/js/openy_hours_formatter.js
  modules/custom/openy_hours_formatter/openy_hours_formatter.info.yml
  modules/custom/openy_hours_formatter/openy_hours_formatter.libraries.yml
  modules/custom/openy_hours_formatter/openy_hours_formatter.module
  modules/custom/openy_hours_formatter/openy_hours_formatter.services.yml
  modules/custom/openy_hours_formatter/src/HoursToday.php
  modules/custom/openy_hours_formatter/src/Plugin/Field/FieldFormatter/CustomHoursToday.php
  modules/custom/openy_hours_formatter/templates/openy-hours-formatter.html.twig
Labels: Backporting, Decoupling, IXM, Level: Middle, PR: Needs Testing, PR: Tested, Type: Task, dependencies
