Repository ymcatwincities/openy, pull requests merged in 2021-04, with the labels that each got.

#2428 Repair footer alerts for Lily & Rose
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/index.js
Labels: Level: Middle, PR: Code Reviewed, PR: Needs Testing, Severity: Important, Type: Bug, dependencies, javascript

#2431 [HOTFIX] Fix Standard install gxp link fail
  modules/custom/openy_gxp/openy_gxp.links.menu.yml
  modules/custom/openy_system/openy_system.links.menu.yml
Labels: Level: Advanced, Severity: Critical, Type: Bug

#2432 Add custom query options to Save button of media image edit form.
  modules/custom/openy_focal_point/openy_focal_point.module
Labels: Type: Bug

#2436 [MAINTAIN-12] Small Banner paragraph should be responsive in Rose theme
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scripts/openy_rose.js
  themes/openy_themes/openy_rose/scss/modules/_paragraphs.scss
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2434 Introduce Daxko v1 GXP PEF Syncer
  composer.json
Labels: Backporting, Level: Advanced, Needs approval, Severity: Important, Type: Feature, dependencies

#2435 Introduce Ynorth gxp spots proxy for GroupEx PRO public api
  composer.json
Labels: Backporting, Level: Advanced, Needs approval, PR: DO NOT MERGE, Type: Experimental feature, dependencies

#2439 Add YN node_session. Keeps Open Y node_session in 0.9 as well
  composer.json
  modules/openy_features/openy_node/modules/openy_node_session/config/install/core.entity_form_display.node.session.default.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/core.entity_form_display.paragraph.session_time.default.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/core.entity_view_display.node.session.default.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/core.entity_view_display.node.session.teaser.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/core.entity_view_display.paragraph.session_time.default.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_activity_type.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_availability.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_productid.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_class.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_description.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_exclusions.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_gender.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_in_mbrsh.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_instructor.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_location.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_max_age.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_mbr_price.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_min_age.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_nmbr_price.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_online.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_plocation.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_reg_link.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_room.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_ticket.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.node.session.field_session_time.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.paragraph.session_time.field_session_time_date.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.field.paragraph.session_time.field_session_time_days.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_activity_type.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_availability.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_productid.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_class.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_description.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_exclusions.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_gender.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_in_mbrsh.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_instructor.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_location.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_max_age.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_mbr_price.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_min_age.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_nmbr_price.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_online.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_plocation.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_reg_link.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_room.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_ticket.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.node.field_session_time.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.paragraph.field_session_time_date.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/field.storage.paragraph.field_session_time_days.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/node.type.session.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/paragraphs.paragraphs_type.session_time.yml
  modules/openy_features/openy_node/modules/openy_node_session/config/install/rabbit_hole.behavior_settings.node_type_session.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.features.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.info.yml
  modules/openy_features/openy_node/modules/openy_node_session/openy_node_session.install
Labels: Backporting, Level: Advanced, PR: Needs Review, PR: Needs Testing, Severity: Important, Type: Feature, dependencies
