Repository ymcatwincities/openy, pull requests merged in 2021-01, with the labels that each got.

#2356 Make Coordinates required field
  modules/openy_features/openy_location/modules/openy_loc_branch/config/install/field.field.node.branch.field_location_coordinates.yml
  modules/openy_features/openy_location/modules/openy_loc_branch/openy_loc_branch.install
  modules/openy_features/openy_location/modules/openy_loc_camp/config/install/field.field.node.camp.field_location_coordinates.yml
  modules/openy_features/openy_location/modules/openy_loc_camp/openy_loc_camp.install
  modules/openy_features/openy_location/modules/openy_loc_facility/config/install/field.field.node.facility.field_location_coordinates.yml
  modules/openy_features/openy_location/modules/openy_loc_facility/openy_loc_facility.install
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Normal, Type: Bug

#2348 Add uninstall hook. Remove dependency from profile.
  openy.info.yml
  openy.install
Labels: Level: Novice, Needs approval, Severity: Critical, Type: Task, dependencies

#2346 fixed the "Today's hours" block time: removed hardcoded keys array for the 'Branch Hours' field; fixed dayOfWeek format
  modules/custom/openy_hours_formatter/js/openy_hours_formatter.js
  modules/custom/openy_hours_formatter/src/Plugin/Field/FieldFormatter/CustomHoursToday.php
Labels: Needs approval, PR: Code Reviewed, PR: Tested, Type: Bug

#2361 Fix twig variable name
  modules/custom/openy_search/openy_google_search/templates/openy-google-search.html.twig
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug

#2358 Getting stable libraries into Open Y
  composer.json
Labels: Level: Middle, Severity: Critical, Type: Task, dependencies

#2366 Use video from Drupal.org. Get rid of last fork dependency in 9.x branch
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Task, dependencies

#2372 Fix #2367
  composer.json
Labels: Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Critical, Type: Bug, dependencies

#2373 9.x 2.x af4 Add demo content Sessions for Camps
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_05.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/openy_demo_nsessions.info.yml
Labels: Level: Advanced, PR: Code Reviewed, PR: DO NOT MERGE, dependencies

#2375 Make mpdf more flexible for us
  composer.json
Labels: Level: Advanced, PR: Code Reviewed, dependencies

#2374 Add demo content for a few facilities
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_06.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/openy_demo_nsessions.info.yml
Labels: Level: Advanced, Type: Bug, dependencies

#2324 Allow 9.0.x and 9.1.x cores for Open Y
  composer.json
Labels: Level: Middle, Needs approval, PR: DO NOT MERGE, Severity: Normal, Type: Task, dependencies

#2378 [YPKCOY-179] Fix for 'Missed alert nid in draggableviews'
  modules/openy_features/openy_node/modules/openy_node_alert/src/Plugin/rest/resource/AlertsRestResource.php
Labels: Five Jars, PR: Needs Review, PR: Needs Testing, Type: Bug

#2379 Disable online availability for having more FULL classes
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_05.yml
Labels: Backporting, Level: Advanced, PR: Code Reviewed, Type: Task

#2381 Update demo_form.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_webform/assets/yml/demo_form.yml
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Type: Bug

#2383 Make a time gap in Activity Finder in order to have 404 test case
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_paragraph_session_time_02.yml
Labels: Level: Advanced, Severity: Important, Type: Task

#2395 Issue #2388 fix try
  modules/custom/openy_repeat/src/RepeatManager.php
  modules/custom/openy_session_instance/openy_session_instance.info.yml
  modules/custom/openy_session_instance/src/SessionInstanceManager.php
Labels: Level: Advanced, PR: Needs Review, Severity: Important, Type: Bug
