Repository ymcatwincities/openy, pull requests merged in 2021-02, with the labels that each got.

#2397 Drush10 ymca sync
  composer.json
  modules/custom/ymca_sync/src/DependencyInjection/Compiler/YmcaSyncPass.php
  modules/custom/ymca_sync/src/Form/SettingsForm.php
  modules/custom/ymca_sync/src/SyncRepository.php
  modules/custom/ymca_sync/src/Syncer.php
  modules/custom/ymca_sync/src/SyncerInterface.php
  modules/custom/ymca_sync/src/SyncerRunner.php
  modules/custom/ymca_sync/src/SyncerTerminateException.php
  modules/custom/ymca_sync/src/YmcaSyncServiceProvider.php
  modules/custom/ymca_sync/ymca_sync.info.yml
  modules/custom/ymca_sync/ymca_sync.links.menu.yml
  modules/custom/ymca_sync/ymca_sync.module
  modules/custom/ymca_sync/ymca_sync.routing.yml
  modules/custom/ymca_sync/ymca_sync.services.yml
Labels: Backporting

#2398 fixed displaying tooltips for the webform element for Carnation theme
  themes/openy_themes/openy_carnation/openy_carnation.libraries.yml
  themes/openy_themes/openy_carnation/templates/form/form-element.html.twig
Labels: Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Important, dependencies, javascript

#2354 Add Activity Finder v4 and keep v3 for optional usage
  modules/custom/openy_daxko2/src/OpenyActivityFinderDaxkoBackend.php
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_05.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_node_session_06.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/config/install/migrate_plus.migration.openy_demo_paragraph_session_time_02.yml
  modules/openy_features/openy_demo_content/modules/openy_demo_nsessions/openy_demo_nsessions.info.yml
Labels: Backporting, Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Important, Type: Feature, dependencies

#2399 Issue #3070132 by Peter Majmesku: Undefined index: changefreq Notice…
  composer.json
Labels: Type: Bug, dependencies

#2401 Fix needed dependency missed for PEF GXP integration
  modules/custom/openy_pef_gxp_sync/openy_pef_gxp_sync.info.yml
Labels: Level: Novice, PR: Code Reviewed, Type: Bug, Type: Task, dependencies

#2404 Return default Focal Point behavior if no paragraph type or field in query params.
  modules/custom/openy_focal_point/src/Plugin/Field/FieldWidget/OpenYFocalPointImageWidget.php
Labels: Level: Middle, Severity: Important, Type: Bug, dependencies

#2408 [PRODDEV-184] fixed a size of buttons on the start screen of AF4 for the mobile screen for the Carnation theme
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/src/scss/modules/_af4.scss
Labels: PR: Code Reviewed, Type: Bug

#2412 Add update_path. Move menu to openy_gxp. Make it main in suite.
  modules/custom/embedded_groupexpro_schedule/embedded_groupexpro_schedule.info.yml
  modules/custom/embedded_groupexpro_schedule/embedded_groupexpro_schedule.install
  modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.info.yml
  modules/custom/openy_group_schedules/modules/groupex_form_cache/groupex_form_cache.install
  modules/custom/openy_group_schedules/openy_group_schedules.info.yml
  modules/custom/openy_group_schedules/openy_group_schedules.install
  modules/custom/openy_gxp/openy_gxp.info.yml
  modules/custom/openy_gxp/openy_gxp.routing.yml
  modules/custom/openy_pef_gxp_sync/openy_pef_gxp_sync.info.yml
  modules/custom/openy_pef_gxp_sync/openy_pef_gxp_sync.install
  modules/custom/openy_system/openy_system.routing.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_embedded_groupexpro_schedule/openy_prgf_embedded_groupexpro_schedule.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_embedded_groupexpro_schedule/openy_prgf_embedded_groupexpro_schedule.install
  modules/openy_features/openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.info.yml
  modules/openy_features/openy_prgf/modules/openy_prgf_group_schedules/openy_prgf_group_schedules.install
Labels: Daxko, Level: Advanced, PR: Code Reviewed, PR: Tested, Severity: Minor, Type: Bug, Type: Task, dependencies

#2414 Carnation Alerts Improvements
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/build/static/js/main.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/AppFooter.js
  modules/openy_features/openy_node/modules/openy_node_alert/js/openy-alerts/src/AppHeader.js
  themes/openy_themes/openy_carnation/dist/css/style.css
  themes/openy_themes/openy_carnation/openy_carnation.libraries.yml
  themes/openy_themes/openy_carnation/src/scss/modules/_site-alert.scss
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing, PR: Tested
