Repository ymcatwincities/openy, pull requests merged in 2021-08, with the labels that each got.

#2527 [MAINTAIN-154] fixed styles for alert's slider in header and footer for mobile screen
  themes/openy_themes/openy_lily/css/style.css
  themes/openy_themes/openy_lily/sass/modules/_alerts.scss
  themes/openy_themes/openy_lily/sass/modules/_page.scss
  themes/openy_themes/openy_lily/sass/state/_state.scss
  themes/openy_themes/openy_rose/css/styles.css
  themes/openy_themes/openy_rose/scss/modules/_alerts.scss
  themes/openy_themes/openy_rose/scss/modules/_page.scss
  themes/openy_themes/openy_rose/scss/state/_state.scss
Labels: Five Jars, PR: Code Reviewed, PR: Tested

#2529 updated the open-y-subprojects/openy_features up to 1.5
  composer.json
Labels: Five Jars, PR: Code Reviewed, PR: Needs Testing

#2528 feat(location titles): Allow & in Location title
  composer.json
Labels: Level: Middle, PR: Code Reviewed, PR: Tested, Type: Bug, dependencies

#2483 feat!: Drupal Core 9.2.3+
  composer.json
  modules/custom/openy_home_branch/openy_home_branch.install
Labels: Type: Enhancement, dependencies

#2524 fix(deps): Patching geysir
  composer.json
Labels: Type: Bug, dependencies

#2531 fix(deps): Update Alerts app js dependencies
  composer.json
Labels: Type: Task, dependencies, Decoupling

#2532 docs(qa,smoke tests): Init smoke tests
  SMOKE_TESTS.md
Labels: PR: Code Reviewed, Level: Middle, Status: Under development, Type: Docs, Severity: Normal

#2535 docs(qa, smoke tests): Add Group Ex Pro/Search integration tests
  modules/custom/embedded_groupexpro_schedule/SMOKE_TESTS.md
  modules/custom/openy_search/SMOKE_TESTS.md
Labels: PR: Code Reviewed, Level: Novice, Type: Docs, Type: Tests

#2536 feat(flexibility): Do not make Open Y dependent from page cache module
  openy.info.yml
Labels: dependencies, Decoupling

#2538 feat(leaflet): Add clustering to Map
  composer.json
Labels: Level: Middle, Type: Enhancement, Severity: Normal, PR: Needs Testing, dependencies, javascript, Backporting

#2537 feat(deprecate): Sunset Open Y Analytics
  modules/custom/openy_analytics/openy_analytics.info.yml
  modules/custom/openy_update/openy_update.info.yml
  openy.info.yml
  openy.install
  src/Form/TermsOfUseForm.php
Labels: Level: Middle, Type: Task, dependencies, Decoupling

#2540 fix(deps): decouple upgrade tool
  composer.json
  modules/custom/openy_upgrade_tool/README.md
  modules/custom/openy_upgrade_tool/config/install/openy_upgrade_tool.settings.yml
  modules/custom/openy_upgrade_tool/config/install/views.view.openy_upgrade_dashboard.yml
  modules/custom/openy_upgrade_tool/config/optional/system.action.apply_active_version.yml
  modules/custom/openy_upgrade_tool/config/optional/system.action.apply_openy_version.yml
  modules/custom/openy_upgrade_tool/config/schema/openy_upgrade_tool.schema.yml
  modules/custom/openy_upgrade_tool/css/dashboard.css
  modules/custom/openy_upgrade_tool/openy_upgrade_log.page.inc
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.info.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.install
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.libraries.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.links.action.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.links.menu.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.links.task.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.module
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.permissions.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.routing.yml
  modules/custom/openy_upgrade_tool/openy_upgrade_tool.services.yml
  modules/custom/openy_upgrade_tool/src/Annotation/ConfigEventIgnore.php
  modules/custom/openy_upgrade_tool/src/ConfigEventIgnoreBase.php
  modules/custom/openy_upgrade_tool/src/ConfigEventIgnorePluginInterface.php
  modules/custom/openy_upgrade_tool/src/ConfigEventIgnorePluginManager.php
  modules/custom/openy_upgrade_tool/src/ConfigParamUpgradeTool.php
  modules/custom/openy_upgrade_tool/src/ConfigUpdater.php
  modules/custom/openy_upgrade_tool/src/Controller/OpenyUpgradeLogController.php
  modules/custom/openy_upgrade_tool/src/Entity/OpenyUpgradeLog.php
  modules/custom/openy_upgrade_tool/src/Entity/OpenyUpgradeLogInterface.php
  modules/custom/openy_upgrade_tool/src/Entity/OpenyUpgradeLogViewsData.php
  modules/custom/openy_upgrade_tool/src/EventSubscriber/ConfigEventSubscriber.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogDeleteForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogDiff.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogManualMerge.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogRevisionDeleteForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogRevisionRevertForm.php
  modules/custom/openy_upgrade_tool/src/Form/OpenyUpgradeLogSettingsForm.php
  modules/custom/openy_upgrade_tool/src/OpenYUpgradeToolFeatureStorage.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogAccessControlHandler.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogHtmlRouteProvider.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogListBuilder.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManager.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogManagerInterface.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogStorage.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeLogStorageInterface.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeToolCachedStorage.php
  modules/custom/openy_upgrade_tool/src/OpenyUpgradeToolRevisionStorage.php
  modules/custom/openy_upgrade_tool/src/Plugin/Action/ApplyCurrentActiveVersionAction.php
  modules/custom/openy_upgrade_tool/src/Plugin/Action/ApplyOpenyVersionAction.php
  modules/custom/openy_upgrade_tool/src/Plugin/ConfigEventIgnore/Views.php
  modules/custom/openy_upgrade_tool/src/Routing/RouteSubscriber.php
  modules/custom/openy_upgrade_tool/templates/openy-upgrade-log.html.twig
Labels: PR: Code Reviewed, Level: Middle, Type: Task, dependencies, Decoupling
