Repository ymcatwincities/openy, pull requests merged in 2021-11, with the labels that each got.

#2580 fix: Remove drupal/core in favor of core-recommended only
  composer.json
Labels: PR: Code Reviewed, Type: Bug

#2581 [MAINTAIN-203] updated the openy_daxko_gxp_syncer module version up to 1.1.1
  composer.json
Labels: PR: Code Reviewed, PR: Tested, Five Jars

#2583 fix: Use Interface, not Object, in _construct
  composer.json
Labels: PR: Code Reviewed, Type: Bug, Severity: Important, dependencies

#2582 [MAINTAIN-131] Install theme's footer block before theme installation.
  openy.profile
Labels: PR: Code Reviewed, PR: Needs Testing, Five Jars

#2579 feat!: Decouple program search
  composer.json
  modules/custom/openy_programs_search/README.md
  modules/custom/openy_programs_search/config/install/openy_programs_search.settings.yml
  modules/custom/openy_programs_search/openy_programs_search.info.yml
  modules/custom/openy_programs_search/openy_programs_search.links.menu.yml
  modules/custom/openy_programs_search/openy_programs_search.module
  modules/custom/openy_programs_search/openy_programs_search.permissions.yml
  modules/custom/openy_programs_search/openy_programs_search.routing.yml
  modules/custom/openy_programs_search/openy_programs_search.services.yml
  modules/custom/openy_programs_search/src/DataStorage.php
  modules/custom/openy_programs_search/src/DataStorageInterface.php
  modules/custom/openy_programs_search/src/Form/ProgramsSearchBlockForm.php
  modules/custom/openy_programs_search/src/Form/SettingsForm.php
  modules/custom/openy_programs_search/src/Plugin/Block/ProgramsSearchBlock.php
  modules/custom/openy_programs_search/tests/src/Unit/StorageTest.php
Labels: PR: DO NOT MERGE, dependencies, Backporting, Decoupling

#2596 fix(cx,ux): Improve description of the field
  modules/custom/openy_field_hours/modules/openy_field_holiday_hours/src/Plugin/Field/FieldWidget/HolidayHoursWidget.php
Labels: Type: Docs, UX
